import {useAuth} from '@clerk/clerk-react';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {WorkspaceHeader} from '../../components/ui/WorkspaceHeader.jsx';
import {WorkspaceTabs} from '../../components/ui/WorkspaceTabs.jsx';
import {ConfirmDialog} from '../../components/ui/ConfirmDialog.jsx';
import {ServiceCallFields,EMPTY_SERVICE_CALL} from '../service-calls/ServiceCallForm.jsx';
import {blankInspection,inspectionProgress,highestPriority,WORKFLOW_LABELS,validateInspection,newId} from './inspectionModel.js';
import {prepareInspectionImport,sha256} from './legacyInspectionImport.js';
import {inspectionApi,downloadBlob,importPhotoFile} from './inspectionApi.js';
import {Field,Select,OverviewEditor,EquipmentEditor,FindingsEditor} from './InspectionEditor.jsx';
import './inspection.css';

// In-memory recovery only: no customer observations are written to browser storage.
const sessionDrafts=new Map();
const TABS=['Overview','Equipment','Findings','Photos','Report'].map(label=>({key:label.toLowerCase(),label}));
export function ElectricalInspectionWorkspace({permissions}){const {getToken,userId}=useAuth();const api=useMemo(()=>inspectionApi(getToken),[getToken]);return <InspectionWorkspaceBody key={userId} sessionKey={userId} api={api} permissions={permissions}/>;}
export function InspectionWorkspaceBody({api,permissions={},sessionKey='fixture'}){
 const navigate=useNavigate(),[params,setParams]=useSearchParams(),selected=params.get('inspection');
 const cacheKey=id=>`${sessionKey}:${id||'new'}`;
 const [rows,setRows]=useState([]),[record,setRecord]=useState(null),[document,setDocument]=useState(null),[tab,setTab]=useState('overview'),[equipmentId,setEquipmentId]=useState('');
 const [search,setSearch]=useState(''),[filter,setFilter]=useState(''),[archived,setArchived]=useState(false),[division,setDivision]=useState(permissions.department||permissions.division||'Electrical');
 const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[reviewDirty,setReviewDirty]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(null);
 const [importPreview,setImportPreview]=useState(null),[allowDuplicate,setAllowDuplicate]=useState(false),[duplicateReason,setDuplicateReason]=useState(''),[uploadQueue,setUploadQueue]=useState([]),[photoMeta,setPhotoMeta]=useState({equipmentId:'',findingId:'',caption:''});
 const [people,setPeople]=useState([]),[assignee,setAssignee]=useState(''),[jobs,setJobs]=useState([]),[jobSearch,setJobSearch]=useState(''),[linkJob,setLinkJob]=useState('');
 const [callForm,setCallForm]=useState(null),[stages,setStages]=useState([]),[calls,setCalls]=useState([]),[callReason,setCallReason]=useState('');
 const [revisionId,setRevisionId]=useState(''),[pdf,setPdf]=useState(null),[photoUrls,setPhotoUrls]=useState({});
 const working=useRef(false),sequence=useRef(0),saveRequest=useRef(null),urlRefs=useRef([]);
 const revoke=()=>{urlRefs.current.forEach(URL.revokeObjectURL);urlRefs.current=[];};
 useEffect(()=>()=>revoke(),[]);
 const load=useCallback(async id=>{const seq=++sequence.current;setLoading(true);try{
  if(id&&id!=='new'){const item=await api.rpc('hi_read',{p_id:id});if(seq!==sequence.current)return;const retained=sessionDrafts.get(cacheKey(id));setRecord(retained?{...item,version:retained.version??item.version}:item);setDocument(structuredClone(retained?.document||item.document));setDirty(!!retained?.dirty);setReviewDirty(!!retained?.reviewDirty);if(retained){setUploadQueue(retained.uploadQueue||[]);setMessage('Recovered unsaved changes from this session.');if(retained.version!==item.version)setError('The saved inspection changed while your local edits were pending. Export your local copy, then discard local changes and reload to compare.');}setAssignee(item.assigned_to);setDivision(item.division);setPdf(null);setPhotoUrls({});revoke();const eligible=await api.rpc('hi_people',{p_id:id});if(seq===sequence.current)setPeople(eligible);}
  else if(!id){const result=[];for(let offset=0;;offset+=100){const page=await api.rpc('hi_read',{p_search:search,p_archived:archived,p_offset:offset});result.push(...page);if(page.length<100)break;}if(seq!==sequence.current)return;setRows(result);setRecord(null);setDocument(null);setDirty(false);}
 }catch(e){if(seq===sequence.current)setError(e.message);}finally{if(seq===sequence.current)setLoading(false);}},[api,archived,search,sessionKey]);
 // Search is applied explicitly. Typing cannot replace a draft or race a save.
 useEffect(()=>{setError('');if(selected!=='new')load(selected);else if(!document){const retained=sessionDrafts.get(cacheKey('new'));setDocument(retained?.document||blankInspection());setImportPreview(retained?.importPreview||null);setRecord(null);setDirty(true);}return()=>{sequence.current++;};},[selected,archived,api]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!dirty&&!reviewDirty&&!uploadQueue.length)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,reviewDirty,uploadQueue.length]);
 const guard=action=>{if(working.current)return;if(dirty||reviewDirty||uploadQueue.length)setConfirm({title:'Leave this inspection?',description:'Unsaved changes and selected uploads remain only in this session. Export a copy or save before leaving.',reason:false,local:()=>{sessionDrafts.delete(cacheKey(selected));setDirty(false);setReviewDirty(false);setUploadQueue([]);action();}});else action();};
 useEffect(()=>{if(!dirty&&!reviewDirty&&!uploadQueue.length)return;const intercept=e=>{const a=e.target.closest?.('a[href]');if(!a||a.download||a.target==='_blank'||e.ctrlKey||e.metaKey)return;const target=new URL(a.href,window.location.href);if(target.origin===window.location.origin&&target.pathname!==window.location.pathname){e.preventDefault();e.stopPropagation();guard(()=>{window.location.assign(target.href);});}};window.document.addEventListener('click',intercept,true);return()=>window.document.removeEventListener('click',intercept,true);},[dirty,reviewDirty,uploadQueue.length]);
 useEffect(()=>{if(!document||!selected||(selected!=='new'&&record?.id!==selected)||(selected==='new'&&record))return;const key=cacheKey(selected);if(dirty||reviewDirty||uploadQueue.length)sessionDrafts.set(key,{document:structuredClone(document),version:record?.version,dirty,reviewDirty,uploadQueue,importPreview});else sessionDrafts.delete(key);},[selected,document,record?.version,dirty,reviewDirty,uploadQueue,importPreview,sessionKey]);
 const change=next=>{setDocument(next);setDirty(true);setPdf(null);setMessage('');};
 async function run(operation){if(working.current)return;working.current=true;setBusy(true);setError('');setMessage('');try{await operation();}catch(e){setError(e.message||String(e));}finally{working.current=false;setBusy(false);}}
 const open=id=>guard(()=>{setParams(id?{inspection:id}:{});setTab('overview');setImportPreview(null);setCallForm(null);setPdf(null);});
 function startNew(preview=null){guard(()=>{const next=preview?.document||blankInspection();setRecord(null);setDocument(structuredClone(next));setDirty(true);setTab('overview');setImportPreview(preview);setUploadQueue([]);setAllowDuplicate(false);setDuplicateReason('');saveRequest.current=null;setParams({inspection:'new'});});}
 async function save(){const errors=validateInspection(document);if(errors.length)throw new Error(errors.join('\n'));const data={p_id:record?.id||null,p_expected_version:record?.version||null,p_document:document,p_division:division,p_import:!record&&importPreview?{source:importPreview.source,sourceHash:importPreview.sourceHash,fileHash:importPreview.fileHash,filename:importPreview.filename}:null,p_allow_duplicate:allowDuplicate,p_reason:duplicateReason};
  const key=JSON.stringify(data);if(saveRequest.current?.key!==key)saveRequest.current={key,id:newId()};const result=await api.rpc('hi_save',{...data,p_request_id:saveRequest.current.id});sessionDrafts.delete(cacheKey(selected));setDirty(false);
  if(!record&&importPreview){const sourceFile=new File([importPreview.originalFile],importPreview.filename,{type:/\.html?$/i.test(importPreview.filename)?'text/html':'application/json'});const queue=[{id:newId(),file:sourceFile,kind:'source',equipmentId:'',findingId:'',caption:'Original imported source'},...importPreview.photos.map(p=>({...p,id:newId(),kind:'photo'}))];setUploadQueue(queue);}
  setRecord(r=>({...r,id:result.id,version:result.version,document}));setParams({inspection:result.id},{replace:true});setImportPreview(null);await load(result.id);setMessage('Inspection saved.');return result;
 }
 function askAction(action,title,data={},description='This action is recorded in inspection history.'){if(dirty){setError('Save changes before this action.');return;}setConfirm({action,title,data,description,reason:action!=='submit',requestId:newId()});}
 async function confirmAction(reason){const item=confirm;if(item.local){setConfirm(null);item.local();return;}await run(async()=>{if(item.fileId){await api.rpc('hi_file_archive',{p_id:item.fileId,p_reason:reason});}else {const result=await api.rpc('hi_action',{p_request_id:item.requestId,p_id:record.id,p_expected_version:record.version,p_action:item.action,p_data:item.data,p_reason:reason||''});if(result.revision_id)setRevisionId(result.revision_id);}sessionDrafts.delete(cacheKey(record.id));setConfirm(null);await load(record.id);setMessage(item.title+' completed.');});}
 async function uploadAll(){if(dirty)throw new Error('Save changes before uploading evidence.');for(const entry of uploadQueue){const file=entry.kind==='photo'?await importPhotoFile(entry.file):entry.file;await api.upload({...entry,file,inspection:record.id,version:record.version});setUploadQueue(queue=>queue.filter(p=>p.id!==entry.id));}sessionDrafts.delete(cacheKey(record.id));await load(record.id);setMessage('Evidence uploaded and verified.');}
 async function previewPhoto(file){if(photoUrls[file.id])return;const blob=await api.download(file.storage_path);if(await sha256(await blob.arrayBuffer())!==file.sha256)throw new Error('Photo verification failed.');const url=URL.createObjectURL(blob);urlRefs.current.push(url);setPhotoUrls(old=>({...old,[file.id]:url}));}
 async function makePdf(){const [{inspectionPdf},{default:logoUrl}]=await Promise.all([import('./inspectionPdf.js'),import('./inspection-report-logo.png?url')]);const logoResponse=await fetch(logoUrl);if(!logoResponse.ok||!logoResponse.headers.get('content-type')?.startsWith('image/png'))throw new Error('The report logo could not be loaded. Please retry.');const logoBytes=await logoResponse.arrayBuffer();const revision=record?.revisions?.find(r=>r.id===revisionId)||null;const doc=revision?.document||document;const files=record?.files?.filter(f=>f.kind==='photo'&&f.status==='ready'&&(!revision||revision.file_ids.includes(f.id)))||[];if(revision&&files.length!==revision.file_ids.length)throw new Error('An issued evidence file is unavailable. Restore access before generating this revision.');const photos=[];for(const f of files){const blob=await api.download(f.storage_path),bytes=await blob.arrayBuffer();if(await sha256(bytes)!==f.sha256)throw new Error('Evidence verification failed: '+f.file_name);photos.push({...f,bytes});}const bytes=await inspectionPdf({inspectionNumber:record?.inspection_number||'Unsaved inspection',document:doc,revision,photos,logoBytes});const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob);urlRefs.current.push(url);setPdf({bytes,blob,url,revision,name:`${record?.inspection_number||'inspection'}-${revision?'revision-'+revision.revision:'draft'}.pdf`,fileId:newId()});}
 async function publishPdf(){if(!pdf?.revision)throw new Error('Select and generate an issued revision first.');await api.upload({id:pdf.fileId,inspection:record.id,version:record.version,file:new File([pdf.blob],pdf.name,{type:'application/pdf'}),kind:'report',revisionId:pdf.revision.id,caption:`${record.inspection_number} — issued revision ${pdf.revision.revision}`});await load(record.id);setMessage('Issued PDF saved to the linked job’s Documents under Service Inspections.');}
 const exportJson=()=>downloadBlob(new Blob([JSON.stringify({format:'northgate-health-inspection-1',document,attachments:record?.files||[],inspectionNumber:record?.inspection_number||null},null,2)],{type:'application/json'}),`${record?.inspection_number||'inspection'}-data.json`);
 function removeEquipment(e){if(document.findings.some(f=>f.equipmentId===e.id)||record?.files?.some(f=>f.equipment_id===e.id)){setError('Move or archive related findings and unissued photos before removing this equipment. Issued evidence must retain its equipment link.');return;}setConfirm({title:'Remove equipment?',description:`Remove ${e.designator||'this equipment'} and its readings from the current draft. Saved history remains available.`,reason:false,local:()=>change({...document,equipment:document.equipment.filter(r=>r.id!==e.id)})});}
 function removeFinding(f){if(record?.files?.some(p=>p.finding_id===f.id)){setError('Archive unissued linked photos before removing the finding. Issued evidence must retain its finding link.');return;}setConfirm({title:'Remove finding?',description:'Remove this finding from the current draft. Saved history remains available.',reason:false,local:()=>change({...document,findings:document.findings.filter(r=>r.id!==f.id)})});}
 async function createCall(){if(callReason.trim().length<3)throw new Error('Enter a reason for creating and linking the call.');const data={call:callForm};const key=JSON.stringify({data,reason:callReason,version:record.version});if(saveRequest.current?.key!==key)saveRequest.current={key,id:newId()};await api.rpc('hi_action',{p_request_id:saveRequest.current.id,p_id:record.id,p_expected_version:record.version,p_action:'create_call',p_data:data,p_reason:callReason});setCallForm(null);await load(record.id);setMessage('Service call created and linked.');}
 const editable=!record||record.can_edit,progress=document?inspectionProgress(document):null;
 const canCreateCall=permissions.can_create_jobs||permissions.canCreateJobs;
 return <div className="hi-workspace"><WorkspaceHeader eyebrow="Add-On Tools" title={document?record?.inspection_number||'New electrical inspection':'Electrical Systems Health Inspection'} description="Record field observations, review findings, and issue a saved report." actions={<div className="hi-actions">{document?<><button className="secondary-button" disabled={busy} onClick={()=>open(null)}>Inspection directory</button><button className="secondary-button" disabled={busy} onClick={exportJson}>Export data</button>{record&&(dirty||reviewDirty)&&<button className="secondary-button" disabled={busy} onClick={()=>setConfirm({title:'Discard local changes?',description:'Reload the saved inspection. Export a local copy first if you need to compare it.',reason:false,local:()=>{sessionDrafts.delete(cacheKey(record.id));setDirty(false);setReviewDirty(false);run(()=>load(record.id));}})}>Discard / reload</button>}{editable&&<button className="primary-button" disabled={busy||loading||(!dirty&&!!record)} onClick={()=>run(save)}>{busy?'Working…':'Save inspection'}</button>}</>:<button className="primary-button" onClick={()=>startNew()} disabled={busy}>New inspection</button>}</div>}/>
 <div className="card hi-content">{error&&<div className="hi-status hi-error" role="alert">{error}</div>}{message&&<p className="hi-status" role="status">{message}</p>}{loading&&<p role="status">Loading inspections…</p>}
 {!document&&<><form className="hi-directory-filter" onSubmit={e=>{e.preventDefault();run(()=>load(null));}}><Field label="Search client, site, technician or inspection" value={search} onChange={setSearch}/><Select label="Workflow" value={filter} onChange={setFilter} options={{'':'All workflows',...WORKFLOW_LABELS}}/><Select label="Show" value={archived?'archived':'active'} onChange={v=>setArchived(v==='archived')} options={{active:'Active inspections',archived:'Archived inspections'}}/><button className="secondary-button" disabled={busy||loading}>Search / refresh</button></form>
 <div className="hi-actions"><label>Import saved JSON or HTML<input type="file" accept=".json,.html,.htm" disabled={busy} onChange={e=>{const file=e.target.files[0];e.target.value='';if(file)run(async()=>{const preview=await prepareInspectionImport(file);setImportPreview({...preview,originalFile:file});});}}/></label></div>
 {importPreview&&<section className="hi-section hi-warning"><h2>Import preview</h2><p>{importPreview.document.client.clientName||'Unnamed client'} · {importPreview.document.equipment.length} equipment records · {importPreview.document.findings.length} findings · {importPreview.photos.length} photos</p><p>{importPreview.warnings.length} review notes. Original data will be preserved when saved.</p><p>Source fingerprint: {importPreview.sourceHash.slice(0,16)}…</p><button className="primary-button" onClick={()=>startNew(importPreview)}>Open imported draft</button><button className="secondary-button" onClick={()=>setImportPreview(null)}>Cancel import</button></section>}
 <div className="hi-table-scroll"><table className="hi-table"><thead><tr><th>Inspection</th><th>Client / site</th><th>Visit</th><th>Technician</th><th>Workflow</th><th>Open priority</th></tr></thead><tbody>{rows.filter(r=>!filter||r.workflow===filter).map(r=><tr key={r.id}><td><button className="secondary-button" onClick={()=>open(r.id)}>{r.inspection_number}</button></td><td><strong>{r.client_name||'Unnamed client'}</strong><br/>{r.site_address}</td><td>{r.visit_date||'Not recorded'}</td><td>{r.technician||'Assigned user'}</td><td>{WORKFLOW_LABELS[r.workflow]}</td><td>{r.priority||'None recorded'}</td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<p className="hi-empty">No inspections match this view.</p>}</>}
 {document&&<><div className="hi-summary"><p><strong>{record?WORKFLOW_LABELS[record.workflow]:'Unsaved draft'}{record?.archived_at?' · Archived':''}</strong>{dirty||reviewDirty?'Unsaved changes':'Saved version '+(record?.version||'—')}</p><p><strong>{progress.percent}% recorded</strong>{progress.unassessed} observations unassessed</p><p><strong>Highest open priority</strong>{highestPriority(document)}</p></div>
 <WorkspaceTabs tabs={TABS} activeKey={tab} onChange={setTab} ariaLabel="Inspection sections"/>
 {tab==='overview'&&<><fieldset className="hi-fieldset" disabled={busy||loading||!editable}><OverviewEditor document={document} onChange={change}/>{!record&&<Select label="Department" value={division} onChange={v=>{setDivision(v);setDirty(true);}} options={{Electrical:'Electrical',Construction:'Construction',Admin:'Admin'}}/>}{importPreview&&<section className="hi-section"><label className="hi-checkbox"><input type="checkbox" checked={allowDuplicate} onChange={e=>setAllowDuplicate(e.target.checked)}/>Create a separate inspection even if this source was imported before</label>{allowDuplicate&&<Field label="Reason for separate import" value={duplicateReason} onChange={setDuplicateReason}/>}</section>}</fieldset>
 {record&&<section className="hi-section"><h2>Assignment and job link</h2><div className="hi-actions"><Select label="Assigned technician" value={assignee} onChange={setAssignee} options={Object.fromEntries(people.map(p=>[p.id,p.name]))}/>{record.can_assign&&editable&&<button className="secondary-button" disabled={busy||dirty||assignee===record.assigned_to} onClick={()=>askAction('assign','Assign technician',{assigned_to:assignee})}>Update assignment</button>}</div>
 <p>{record.job?`Linked to ${record.job.number} — ${record.job.name}`:'No job or service call linked.'}</p>{record.job&&<button className="secondary-button" onClick={()=>guard(()=>navigate('/jobs',{state:{openJobId:record.job.id}}))}>Open linked job / call</button>}
 {editable&&<><div className="hi-actions"><Field label="Find existing job or service call" value={jobSearch} onChange={setJobSearch}/><button className="secondary-button" disabled={busy||dirty} onClick={()=>run(async()=>setJobs(await api.rpc('hi_jobs',{p_search:jobSearch})))}>Find</button></div>{!!jobs.length&&<div className="hi-actions"><Select label="Job / service call" value={linkJob} onChange={setLinkJob} blank options={Object.fromEntries(jobs.map(j=>[j.id,`${j.number} — ${j.name} (${j.division})`]))}/><button className="secondary-button" disabled={!linkJob||busy||dirty} onClick={()=>askAction('link','Link inspection',{job_id:linkJob,confirmed_snapshot:true},'Confirm this job is the intended parent. The original client/site snapshot and all previously issued reports remain unchanged.')}>Review link</button></div>}
 {canCreateCall&&!callForm&&<button className="secondary-button" disabled={busy||dirty} onClick={()=>run(async()=>{const [s,c]=await Promise.all([api.rpc('svc_read_stages'),api.rpc('svc_read_calls',{p_archived:false,p_offset:0,p_limit:200})]);setStages(s);setCalls(c);setCallForm({...EMPTY_SERVICE_CALL,division:record.division,name:document.client.clientName,business_name:document.client.clientName,contact_name:document.client.contactName,phone:document.client.contactPhone,billing_email:document.client.contactEmail,address_line1:document.client.siteAddress,description:document.scope,service_date:document.visitDate});setCallReason('');})}>Create and link service call</button>}
 {callForm&&<form className="svc-workspace" onSubmit={e=>{e.preventDefault();run(createCall);}}><fieldset className="hi-fieldset" disabled={busy}><ServiceCallFields form={callForm} change={(key,value)=>setCallForm(f=>({...f,[key]:value}))} stages={stages} calls={calls}/><Field label="Reason for creating and linking this call" value={callReason} onChange={setCallReason} required/><div className="hi-actions"><button className="primary-button">Create and link service call</button><button type="button" className="secondary-button" onClick={()=>setCallForm(null)}>Cancel</button></div></fieldset></form>}</>}</section>}
 {record&&<section className="hi-section"><h2>History</h2>{record.history?.map((h,i)=><p key={i}><strong>{h.user_name}</strong> · {new Date(h.created_at).toLocaleString()}<br/>{h.note}</p>)}<div className="hi-actions"><button className="secondary-button" disabled={busy} onClick={()=>run(async()=>{const original=await api.rpc('hi_original',{p_id:record.id});if(!original)throw new Error('This inspection was not imported.');downloadBlob(new Blob([JSON.stringify(original,null,2)],{type:'application/json'}),`${record.inspection_number}-original.json`);})}>Download original import data</button>{(permissions.can_archive_records||permissions.canArchiveRecords)&&<button className="secondary-button" disabled={busy||dirty} onClick={()=>askAction(record.archived_at?'restore':'archive',record.archived_at?'Restore inspection':'Archive inspection')}>{record.archived_at?'Restore inspection':'Archive inspection'}</button>}</div></section>}</>}
 {tab==='equipment'&&<fieldset className="hi-fieldset" disabled={busy||loading||!editable}><EquipmentEditor document={document} onChange={change} selectedId={equipmentId} onSelect={setEquipmentId} onError={setError} onRemove={removeEquipment}/></fieldset>}
 {tab==='findings'&&<fieldset className="hi-fieldset" disabled={busy||loading||!editable}><FindingsEditor document={document} onChange={change} onRemove={removeFinding}/></fieldset>}
 {tab==='photos'&&<><h2>Photos and evidence</h2>{editable&&<fieldset className="hi-fieldset" disabled={busy||!record||dirty}><p>Save the draft before selecting evidence. Uploaded evidence is protected and retained with issued revisions.</p><div className="hi-grid"><Select label="Equipment" value={photoMeta.equipmentId} onChange={v=>setPhotoMeta(p=>({...p,equipmentId:v,findingId:''}))} blank options={Object.fromEntries(document.equipment.map(e=>[e.id,e.designator]))}/><Select label="Finding" value={photoMeta.findingId} onChange={v=>setPhotoMeta(p=>({...p,findingId:v}))} blank options={Object.fromEntries(document.findings.filter(f=>!photoMeta.equipmentId||f.equipmentId===photoMeta.equipmentId).map((f,i)=>[f.id,`${i+1}: ${f.description.slice(0,60)}`]))}/><Field label="Caption" value={photoMeta.caption} onChange={v=>setPhotoMeta(p=>({...p,caption:v}))}/><label>Select photos<input type="file" accept="image/jpeg,image/png" multiple onChange={e=>{const files=[...e.target.files];setUploadQueue(q=>[...q,...files.map(file=>({...photoMeta,file,id:newId(),kind:'photo'}))]);e.target.value='';}}/></label></div></fieldset>}
 {!!uploadQueue.length&&<section className="hi-section hi-warning"><h3>Selected uploads</h3>{uploadQueue.map(p=><p key={p.id}>{p.file.name} · {(p.file.size/1024).toFixed(0)} KB</p>)}<button className="primary-button" disabled={busy||dirty} onClick={()=>run(uploadAll)}>Upload / retry selected files</button></section>}
 <div className="hi-photo-grid">{record?.files?.map(f=><article key={f.id} className="hi-photo"><strong>{f.file_name}</strong><p>{f.caption}</p><p>{f.kind} · {f.status}</p>{photoUrls[f.id]&&<img alt={f.caption||'Inspection evidence'} src={photoUrls[f.id]}/>}<div className="hi-actions">{f.kind==='photo'&&f.status==='ready'&&<button className="secondary-button" disabled={busy} onClick={()=>run(()=>previewPhoto(f))}>View photo</button>}{f.status==='ready'&&<button className="secondary-button" disabled={busy} onClick={()=>run(async()=>downloadBlob(await api.download(f.storage_path),f.file_name))}>Download</button>}{f.status==='pending'&&<label>Retry original file<input type="file" disabled={busy||!editable} onChange={e=>{const file=e.target.files[0];if(file)run(async()=>{await api.upload({id:f.id,inspection:record.id,version:record.version,file:new File([file],f.file_name,{type:f.mime_type}),kind:f.kind,equipmentId:f.equipment_id||'',findingId:f.finding_id||'',caption:f.caption,revisionId:f.revision_id});await load(record.id);});}}/></label>}{((editable&&f.kind!=='report')||(record.can_review&&f.kind==='report'&&f.status==='pending'))&&!record.revisions?.some(r=>r.file_ids.includes(f.id))&&<button className="secondary-button" disabled={busy||dirty} onClick={()=>setConfirm({title:'Archive unissued evidence?',description:'The stored original remains retained. This evidence will be excluded from the current draft.',reason:true,fileId:f.id})}>Archive</button>}</div></article>)}</div></>}
 {tab==='report'&&<><section className="hi-section"><h2>Review and issue</h2><fieldset className="hi-fieldset" disabled={busy||(!editable&&!(record?.can_review&&record.workflow==='ready_for_review'&&!record.archived_at))}><div className="hi-grid"><Field label="Reviewer assessment" value={document.assessment} onChange={v=>{if(editable)change({...document,assessment:v});else{setDocument(d=>({...d,assessment:v}));setReviewDirty(true);setPdf(null);}}} multiline/><Field label="Review summary" value={document.reviewSummary} onChange={v=>{if(editable)change({...document,reviewSummary:v});else{setDocument(d=>({...d,reviewSummary:v}));setReviewDirty(true);setPdf(null);}}} multiline/></div></fieldset><p>Issue requires reviewer authority. The issued revision freezes observations, findings and evidence. Later corrections create a new revision.</p>
 <div className="hi-actions">{record&&editable&&<button className="primary-button" disabled={busy||dirty||uploadQueue.length>0} onClick={()=>askAction('submit','Submit for review',{},'Submit the saved inspection for reviewer assessment. Field edits pause until it is returned or issued.')}>Submit for review</button>}{record?.can_review&&record.workflow==='ready_for_review'&&!record.archived_at&&<><button className="primary-button" disabled={busy||dirty} onClick={()=>{const problems=validateInspection(document,{issue:true});if(problems.length){setError(problems.join('\n'));return;}askAction('issue','Issue inspection',{assessment:document.assessment,reviewSummary:document.reviewSummary},'Confirm your assessment and issue this exact saved inspection as an immutable report revision.');}}>Issue revision</button><button className="secondary-button" disabled={busy} onClick={()=>askAction('return','Return for corrections')}>Return for corrections</button></>}{record?.can_review&&record.workflow==='issued'&&!record.archived_at&&<button className="secondary-button" disabled={busy} onClick={()=>askAction('revise','Start revised draft')}>Start revised draft</button>}</div></section>
 <section className="hi-section hi-report-options"><h2>Report preview and export</h2><Select label="Report version" value={revisionId} onChange={v=>{setRevisionId(v);setPdf(null);}} options={{'':'Current draft (not issued)',...Object.fromEntries((record?.revisions||[]).map(r=>[r.id,`Issued revision ${r.revision} — ${new Date(r.issued_at).toLocaleString()}`]))}}/><div className="hi-actions"><button className="secondary-button" disabled={busy||loading} onClick={()=>run(makePdf)}>Generate preview</button>{pdf&&<><button className="secondary-button" onClick={()=>downloadBlob(pdf.blob,pdf.name)}>Download PDF</button>{pdf.revision?.job_snapshot&&record.can_review&&<button className="primary-button" disabled={busy||dirty} onClick={()=>run(publishPdf)}>Save PDF to job Documents</button>}</>}</div>{pdf&&<iframe title="Inspection PDF preview" className="hi-preview" src={pdf.url}/>}</section></>}
 </>}
 </div><ConfirmDialog open={!!confirm} title={confirm?.title||''} description={confirm?.description||''} requireReason={confirm?.reason??true} reasonHint="Enter at least 3 characters. Recorded in history." isSubmitting={busy} onCancel={()=>setConfirm(null)} onConfirm={confirmAction}/></div>;
}
