import {blankEquipment,blankFeeder,blankFinding,blankReading,resizeCircuits,READING_STATES,RESPONSE_STATES,FINDING_CATEGORIES,PRIORITIES,equipmentProgress} from './inspectionModel.js';
export function Field({label,value,onChange,type='text',multiline=false,...props}){return <label className={multiline?'hi-wide':''}><span>{label}</span>{multiline?<textarea rows={3} value={value??''} onChange={e=>onChange(e.target.value)} {...props}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...props}/>}</label>;}
export function Select({label,value,onChange,options,blank=false}){return <label><span>{label}</span><select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value)}>{blank&&<option value="">Not selected</option>}{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;}
export function OverviewEditor({document,onChange}){
 const set=(key,value)=>onChange({...document,[key]:value});
 return <><section className="hi-section"><h2>Client and visit</h2><div className="hi-grid">
 {Object.entries({clientName:'Client name',siteAddress:'Site address',contactName:'Contact',contactPhone:'Phone',contactEmail:'Email',jobNumber:'Historical job reference',visitNotes:'Visit notes'}).map(([key,label])=><Field key={key} label={label} value={document.client[key]} onChange={value=>set('client',{...document.client,[key]:value})} multiline={key==='visitNotes'}/>)}
 <Field label="Visit date" type="date" value={document.visitDate} onChange={v=>set('visitDate',v)}/><Field label="Visit time" value={document.visitTime} onChange={v=>set('visitTime',v)}/><Field label="Time zone" value={document.timeZone} onChange={v=>set('timeZone',v)}/><Field label="Legacy technician (source text)" value={document.technicianLegacy} onChange={v=>set('technicianLegacy',v)}/>
 </div></section><section className="hi-section"><h2>Scope and conditions</h2><div className="hi-grid">{[['scope','Included scope'],['optionalScope','Additional scope'],['limitations','Access and scope limitations'],['conditions','Conditions at the visit']].map(([key,label])=><Field key={key} label={label} value={document[key]} onChange={v=>set(key,v)} multiline/>)}</div></section>
 {!!document.importWarnings.length&&<section className="hi-section hi-warning"><h2>Import review</h2><p>Original saved data is preserved. Record how each difference or unknown was resolved before issuing a report.</p>{document.importWarnings.map((w,i)=><div key={w.id} className="hi-warning-item"><strong>{w.path}</strong><p>{w.message}</p><Field label="Review resolution" value={w.resolution} onChange={v=>set('importWarnings',document.importWarnings.map((r,n)=>n===i?{...r,resolution:v}:r))}/></div>)}</section>}</>;
}
function Reading({reading:r,onChange,compact=false}){
 const set=(key,value)=>onChange({...r,[key]:value});
 return <div className={'hi-reading'+(compact?' hi-reading--compact':'')}>
 {!compact&&<><Field label="Reading label" value={r.label} onChange={v=>set('label',v)}/><Field label={r.kind==='voltage'?'Conductor pair (e.g. A-N)':'Conductor'} value={r.conductor} onChange={v=>set('conductor',v)}/></>}
 <Select label="Observation" value={r.state} onChange={v=>onChange({...r,state:v,value:v==='measured'?r.value:''})} options={READING_STATES}/>
 <Field label="Value" value={r.value} onChange={v=>onChange({...r,value:v,state:v.trim()?'measured':'not_recorded'})} inputMode="decimal"/>
 {r.kind==='temperature'?<Select label="Unit" value={r.unit} onChange={v=>set('unit',v)} options={{F:'°F',C:'°C'}}/>:<span className="hi-unit">{r.unit}</span>}
 <Field label="Reason / limitation" value={r.reason} onChange={v=>set('reason',v)}/>
 </div>;
}
export function EquipmentEditor({document,onChange,selectedId,onSelect,onError,onRemove}){
 const equipment=document.equipment.find(e=>e.id===selectedId)||document.equipment[0];
 const update=next=>onChange({...document,equipment:document.equipment.map(e=>e.id===next.id?next:e)});
 const set=(key,value)=>update({...equipment,[key]:value});
 function add(){const e=blankEquipment();onChange({...document,equipment:[...document.equipment,e]});onSelect(e.id);}
 return <><div className="hi-actions"><label>Equipment<select value={equipment?.id||''} onChange={e=>onSelect(e.target.value)}>{!document.equipment.length&&<option value="">No equipment yet</option>}{document.equipment.map((e,i)=><option key={e.id} value={e.id}>{e.designator||`Equipment ${i+1}`}</option>)}</select></label><button type="button" className="secondary-button" onClick={add}>Add equipment</button>{equipment&&<button type="button" className="secondary-button" onClick={()=>onRemove(equipment)}>Remove equipment</button>}</div>
 {equipment&&<><section className="hi-section"><h2>{equipment.designator||'Equipment setup'}</h2><p>{equipmentProgress(equipment).percent}% of observations recorded. Blank readings remain unassessed.</p><div className="hi-grid">{Object.entries({designator:'Designator',equipmentType:'Equipment type',nominalVoltage:'Nominal voltage',amperage:'Equipment rating',mainConfig:'Main configuration',phaseConfig:'Phase configuration',phaseRotation:'Phase rotation',faultCurrent:'Available fault current',faultCurrentDate:'Fault current date',visitDate:'Equipment visit date',visitTime:'Equipment visit time'}).map(([key,label])=><Field key={key} label={label} type={key==='visitDate'?'date':'text'} value={equipment[key]} onChange={v=>set(key,v)}/>)}
 <Field label="Configured circuit positions" value={equipment.circuitCount} type="number" min={1} max={168} onChange={v=>{try{update(resizeCircuits(equipment,v));}catch(e){onError(e.message);}}}/>
 {Object.entries({notes:'Equipment notes',thermalNotes:'Thermal observations',voltageNotes:'Voltage observations',unassessedReason:'Reason for observations left unassessed'}).map(([key,label])=><Field key={key} label={label} multiline value={equipment[key]} onChange={v=>set(key,v)}/>)}</div></section>
 {['visual','labeling'].map(key=><section className="hi-section" key={key}><h2>{key==='visual'?'Visual checklist':'Labeling checklist'}</h2>{equipment[key].map((r,i)=><div className="hi-check" key={r.id}><strong>{r.label}</strong><Select label="Response" value={r.state} onChange={v=>set(key,equipment[key].map((c,n)=>n===i?{...c,state:v}:c))} options={RESPONSE_STATES}/><Field label="Notes / reason" value={r.notes} onChange={v=>set(key,equipment[key].map((c,n)=>n===i?{...c,notes:v}:c))}/>{r.state==='attention'&&<button type="button" className="secondary-button" onClick={()=>onChange({...document,findings:[...document.findings,{...blankFinding(equipment.id),checklistId:r.id,description:r.label+(r.notes?' — '+r.notes:'')}]})}>Add finding</button>}</div>)}</section>)}
 <section className="hi-section"><h2>Feeder observations</h2>{equipment.feeders.map((f,index)=><details className="hi-detail" key={f.id} open><summary>Feeder {index+1}</summary><div className="hi-grid">{Object.entries({sets:'Sets',size:'Conductor size',material:'Material',insulation:'Insulation'}).map(([key,label])=><Field key={key} label={label} value={f[key]} onChange={v=>set('feeders',equipment.feeders.map(row=>row.id===f.id?{...row,[key]:v}:row))}/>)}</div>{f.readings.map(r=><Reading key={r.id} reading={r} onChange={next=>set('feeders',equipment.feeders.map(row=>row.id===f.id?{...row,readings:row.readings.map(a=>a.id===r.id?next:a)}:row))}/>)}</details>)}<button type="button" className="secondary-button" onClick={()=>set('feeders',[...equipment.feeders,blankFeeder()])}>Add feeder</button></section>
 <section className="hi-section"><h2>Additional readings</h2>{equipment.readings.map(r=><Reading key={r.id} reading={r} onChange={next=>set('readings',equipment.readings.map(row=>row.id===r.id?next:row))}/>)}<div className="hi-actions">{['temperature','current','voltage'].map(kind=><button key={kind} type="button" className="secondary-button" onClick={()=>set('readings',[...equipment.readings,blankReading(kind)])}>Add {kind}</button>)}</div></section>
 <section className="hi-section"><h2>Circuit observations</h2><p>Record measured values with their units. Zero is a measurement; an empty value is not.</p><div className="hi-table-scroll"><table className="hi-table"><thead><tr><th>Circuit</th><th>Breaker A</th><th>Wire size</th><th>Poles</th><th>Description</th><th>Temperature / observation</th></tr></thead><tbody>{equipment.circuits.map(c=>{const patch=values=>set('circuits',equipment.circuits.map(row=>row.id===c.id?{...row,...values}:row));return <tr key={c.id}><th scope="row">{c.number}</th>{['breakerAmps','wireSize','poles','description'].map(key=><td key={key}><input aria-label={`Circuit ${c.number} ${key}`} value={c[key]} onChange={e=>patch({[key]:e.target.value})}/></td>)}<td><Reading reading={c.temperature} compact onChange={temperature=>patch({temperature})}/></td></tr>;})}</tbody></table></div></section></>}
 </>;
}
export function FindingsEditor({document,onChange,onRemove}){
 const patch=(id,values)=>onChange({...document,findings:document.findings.map(f=>f.id===id?{...f,...values}:f)});
 return <><div className="hi-actions"><h2>Findings and corrective actions</h2><button type="button" className="secondary-button" onClick={()=>onChange({...document,findings:[...document.findings,blankFinding()]})}>Add finding</button></div>{!document.findings.length&&<p>No findings recorded.</p>}{document.findings.map((f,i)=><section className="hi-section" key={f.id}><h3>Finding {i+1}</h3><div className="hi-grid"><Select label="Equipment" value={f.equipmentId} onChange={v=>patch(f.id,{equipmentId:v,checklistId:''})} blank options={Object.fromEntries(document.equipment.map((e,i)=>[e.id,e.designator||`Equipment ${i+1}`]))}/><Select label="Category" value={f.category} onChange={v=>patch(f.id,{category:v})} blank options={FINDING_CATEGORIES}/><Select label="Priority" value={f.priority} onChange={v=>patch(f.id,{priority:v})} blank options={Object.fromEntries(PRIORITIES.map(p=>[p,p]))}/>{f.legacySeverity&&<p>Original severity: {f.legacySeverity}</p>}
 {Object.entries({description:'Observation',recommendation:'Recommended action',codeReference:'Code reference (when applicable)',correctionEvidence:'Correction evidence / follow-up'}).map(([key,label])=><Field key={key} label={label} value={f[key]} multiline onChange={v=>patch(f.id,{[key]:v})}/>)}<label className="hi-checkbox"><input type="checkbox" checked={f.completed} onChange={e=>patch(f.id,{completed:e.target.checked})}/>Correction completed</label></div><button type="button" className="secondary-button" onClick={()=>onRemove(f)}>Remove finding</button></section>)}</>;
}
