import {useAuth} from '@clerk/clerk-react';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ConfirmDialog} from '../../components/ui/ConfirmDialog.jsx';
import {inspectionApi} from './inspectionApi.js';
import {Field,Select} from './InspectionEditor.jsx';
import {safePortalUrl,WORKFLOW_LABELS,newId} from './inspectionModel.js';
import './inspection.css';

const PERMIT={permit_number:'',portal_url:'',permit_type:'',jurisdiction:'',status:'',applied_date:'',issued_date:'',expiration_date:'',notes:'',document_ids:[]};
const ATTEMPT={name:'',kind:'jurisdiction',permit_id:'',scheduled_at:'',completed_date:'',status:'Not scheduled',result:'',inspector:'',notes:'',previous_attempt_id:'',document_ids:[]};
const options=values=>Object.fromEntries(values.map(v=>[v,v]));
export function JobPermitRegister({job,permissions,onPanelState}){const {getToken}=useAuth();const api=useMemo(()=>inspectionApi(getToken),[getToken]);return <JobPermitRegisterBody key={job.id} job={job} permissions={permissions} api={api} onPanelState={onPanelState}/>;}
export function JobPermitRegisterBody({job,permissions={},api,onPanelState}){
 const navigate=useNavigate(),[data,setData]=useState(null),[archived,setArchived]=useState(false),[form,setForm]=useState(null),[kind,setKind]=useState('permit'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(null);
 const working=useRef(false),request=useRef(null),seq=useRef(0);
 const load=useCallback(async()=>{const n=++seq.current;const result=await api.rpc('hi_job_register',{p_job_id:job.id,p_archived:archived});if(n===seq.current)setData(result);},[api,job.id,archived]);
 useEffect(()=>{load().catch(e=>setError(e.message));return()=>{seq.current++;};},[load]);
 useEffect(()=>{onPanelState?.({dirty:!!form,busy});},[form,busy,onPanelState]);
 useEffect(()=>{if(!form)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[form]);
 useEffect(()=>{if(!form)return;const intercept=e=>{const a=e.target.closest?.('a[href]');if(!a||a.download||a.target==='_blank'||e.ctrlKey||e.metaKey)return;const url=new URL(a.href,location.href);if(url.origin===location.origin&&url.pathname!==location.pathname){e.preventDefault();e.stopPropagation();setConfirm({cancel:true,title:'Discard register edits?',description:'Leave this form and return to saved records.',destination:url.href});}};document.addEventListener('click',intercept,true);return()=>document.removeEventListener('click',intercept,true);},[form]);
 async function run(fn){if(working.current)return;working.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{working.current=false;setBusy(false);}}
 function begin(type,row=null){setKind(type);setForm(structuredClone(row|| (type==='permit'?PERMIT:ATTEMPT)));request.current=null;setError('');}
 const patch=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function save(){const next={...form};if(kind==='permit')next.portal_url=safePortalUrl(next.portal_url);if(kind==='inspection'&&next.scheduled_at){const date=new Date(next.scheduled_at);if(Number.isNaN(date.getTime()))throw new Error('Enter a valid inspection date and time.');next.scheduled_at=date.toISOString();}
  const args={p_job_id:job.id,p_kind:kind,p_id:form.id||null,p_expected_version:form.version||null,p_data:next};const key=JSON.stringify(args);if(request.current?.key!==key)request.current={key,id:newId()};await api.rpc('hi_job_register_save',{...args,p_request_id:request.current.id});setForm(null);await load();setMessage(kind==='permit'?'Permit saved.':'Inspection attempt saved.');}
 async function confirmAction(reason){const item=confirm;if(item.cancel){setForm(null);setConfirm(null);if(item.destination)window.location.assign(item.destination);return;}await run(async()=>{await api.rpc('hi_job_register_save',{p_request_id:item.requestId,p_job_id:job.id,p_kind:item.kind,p_id:item.row.id,p_expected_version:item.row.version,p_data:{},p_action:archived?'restore':'archive',p_reason:reason});setConfirm(null);await load();setMessage('Register updated.');});}
 const canArchive=permissions.canArchiveRecords||permissions.can_archive_records;
 const linkDocs=ids=><div>{ids?.map(id=>{const d=data.documents.find(d=>d.id===id);return <span key={id} className="hi-muted">{d?.name||'Linked document unavailable'}<br/></span>;})}</div>;
 return <section className="hi-register"><h2>Permits & inspections</h2><p>Track permit numbers, jurisdiction visits and follow-up attempts for this {job.job_type==='service_call'?'service call':'job'}.</p>{error&&<p role="alert" className="hi-status hi-error">{error}</p>}{message&&<p role="status" className="hi-status">{message}</p>}{!data&&<p>Loading permit register…</p>}
 {!form&&<div className="hi-actions">{data?.can_edit&&!archived&&<><button className="primary-button" disabled={busy} onClick={()=>begin('permit')}>Add permit</button><button className="secondary-button" disabled={busy} onClick={()=>begin('inspection')}>Add inspection attempt</button></>}<Select label="Show" value={archived?'archived':'active'} onChange={v=>setArchived(v==='archived')} options={{active:'Active records',archived:'Archived records'}}/><button className="secondary-button" disabled={busy} onClick={()=>run(load)}>Refresh</button></div>}
 {form&&<form onSubmit={e=>{e.preventDefault();run(save);}}><fieldset className="hi-fieldset" disabled={busy||!data?.can_edit}><h3>{form.id?'Edit':'Add'} {kind==='permit'?'permit':'inspection attempt'}</h3><div className="hi-grid">
 {kind==='permit'?<><Field label="Permit number" value={form.permit_number} onChange={v=>patch('permit_number',v)} required maxLength={150}/><Field label="Permit portal URL (optional)" value={form.portal_url} onChange={v=>patch('portal_url',v)} type="url"/><Field label="Permit type" value={form.permit_type} onChange={v=>patch('permit_type',v)}/><Field label="Jurisdiction" value={form.jurisdiction} onChange={v=>patch('jurisdiction',v)}/><Select label="Status (optional)" value={form.status} onChange={v=>patch('status',v)} blank options={options(['Applied','Issued','Closed','Expired','Cancelled'])}/>{[['applied_date','Applied'],['issued_date','Issued'],['expiration_date','Expires']].map(([key,label])=><Field key={key} label={label} type="date" value={form[key]} onChange={v=>patch(key,v)}/>)}</>:<><Field label="Inspection name" value={form.name} onChange={v=>patch('name',v)} required maxLength={200}/><Select label="Type" value={form.kind} onChange={v=>patch('kind',v)} options={{jurisdiction:'Jurisdiction inspection',other:'Other inspection'}}/><Select label="Permit (optional)" value={form.permit_id} onChange={v=>patch('permit_id',v)} blank options={Object.fromEntries((data?.permits||[]).map(p=>[p.id,p.permit_number]))}/><Field label="Scheduled date/time (include time zone, e.g. 2026-09-15T09:00-04:00)" value={form.scheduled_at} onChange={v=>patch('scheduled_at',v)} placeholder="YYYY-MM-DDTHH:mm-04:00"/><Field label="Completed date" type="date" value={form.completed_date} onChange={v=>patch('completed_date',v)}/><Select label="Status" value={form.status} onChange={v=>patch('status',v)} options={options(['Not scheduled','Scheduled','Completed','Cancelled'])}/><Select label="Result (optional)" value={form.result} onChange={v=>patch('result',v)} blank options={options(['Passed','Failed','Partial'])}/><Field label="Inspector" value={form.inspector} onChange={v=>patch('inspector',v)}/>{form.previous_attempt_id&&<p>Reinspection of an earlier failed or partial attempt. Its history stays intact.</p>}</>}
 <Field label="Notes" multiline value={form.notes} onChange={v=>patch('notes',v)}/><fieldset className="hi-wide"><legend>Linked job Documents (optional)</legend>{data?.documents.map(d=><label className="hi-checkbox" key={d.id}><input type="checkbox" checked={form.document_ids?.includes(d.id)||false} onChange={e=>patch('document_ids',e.target.checked?[...(form.document_ids||[]),d.id]:form.document_ids.filter(id=>id!==d.id))}/>{d.name}</label>)}{!data?.documents.length&&<p>Add files in this job’s Documents tab first.</p>}</fieldset></div><div className="hi-actions"><button className="primary-button">Save {kind==='permit'?'permit':'attempt'}</button><button type="button" className="secondary-button" onClick={()=>setConfirm({cancel:true,title:'Discard register edits?',description:'Return to the saved register.'})}>Cancel</button></div></fieldset></form>}
 {!form&&data&&<><h3>Permits</h3>{!data.permits.length?<p>No {archived?'archived ':''}permits recorded. Permit information is optional.</p>:<div className="hi-table-scroll"><table className="hi-table"><thead><tr><th>Permit</th><th>Jurisdiction / type</th><th>Status</th><th>Dates / documents</th><th>Actions</th></tr></thead><tbody>{data.permits.map(p=><tr key={p.id}><td><strong>{p.permit_number}</strong>{p.portal_url&&<p><a href={safePortalUrl(p.portal_url)} target="_blank" rel="noopener noreferrer">Open permit portal</a></p>}</td><td>{p.jurisdiction}<br/>{p.permit_type}</td><td>{p.status||'Not recorded'}</td><td>Applied: {p.applied_date||'—'}<br/>Issued: {p.issued_date||'—'}<br/>Expires: {p.expiration_date||'—'}{linkDocs(p.document_ids)}<p>{p.notes}</p></td><td>{data.can_edit&&<div className="hi-actions">{!archived&&<button className="secondary-button" onClick={()=>begin('permit',p)}>Edit</button>}{canArchive&&<button className="secondary-button" onClick={()=>setConfirm({kind:'permit',row:p,requestId:newId(),title:archived?'Restore permit?':'Archive permit?',description:'Inspection attempts and history are retained.'})}>{archived?'Restore':'Archive'}</button>}</div>}</td></tr>)}</tbody></table></div>}
 <h3>Inspection attempts</h3>{!data.inspections.length?<p>No {archived?'archived ':''}inspection attempts recorded.</p>:<div className="hi-table-scroll"><table className="hi-table"><thead><tr><th>Inspection</th><th>Permit</th><th>Schedule / completion</th><th>Status / result</th><th>Actions</th></tr></thead><tbody>{data.inspections.map(i=><tr key={i.id}><td><strong>{i.name}</strong><br/>{i.inspector}<p>{i.notes}</p>{i.previous_attempt_id&&<small>Reinspection</small>}{linkDocs(i.document_ids)}</td><td>{data.permits.find(p=>p.id===i.permit_id)?.permit_number||(i.permit_id?'Archived permit':'Unlinked')}</td><td>{i.scheduled_at?new Date(i.scheduled_at).toLocaleString():'Not scheduled'}<br/>Completed: {i.completed_date||'—'}</td><td>{i.status}<br/>{i.result||'No result'}</td><td>{data.can_edit&&<div className="hi-actions">{!archived&&<><button className="secondary-button" onClick={()=>begin('inspection',i)}>Edit</button>{['Failed','Partial'].includes(i.result)&&<button className="secondary-button" onClick={()=>begin('inspection',{...ATTEMPT,name:i.name,kind:i.kind,permit_id:i.permit_id||'',previous_attempt_id:i.id})}>Record reinspection</button>}</>}{canArchive&&<button className="secondary-button" onClick={()=>setConfirm({kind:'inspection',row:i,requestId:newId(),title:archived?'Restore inspection attempt?':'Archive inspection attempt?',description:'The recorded result and audit history remain retained.'})}>{archived?'Restore':'Archive'}</button>}</div>}</td></tr>)}</tbody></table></div>}
 <h3>Electrical health inspections</h3><p>Health reports document equipment observations. They do not mark a permit passed or closed.</p>{data.health.map(h=><p key={h.id}><button className="secondary-button" onClick={()=>navigate(`/electrical-inspections?inspection=${h.id}`)}>{h.number}</button> · {WORKFLOW_LABELS[h.workflow]} · {h.visit_date||'Date not recorded'}</p>)}{!data.health.length&&<p>No linked health inspections available within your access.</p>}</>}
 <ConfirmDialog open={!!confirm} title={confirm?.title||''} description={confirm?.description||''} requireReason={!confirm?.cancel} reasonHint="Enter at least 3 characters." isSubmitting={busy} onCancel={()=>setConfirm(null)} onConfirm={confirmAction}/></section>;
}
