import { useAuth } from '@clerk/clerk-react';
import { Copy, FilePlus2, FolderOpen, Printer, RefreshCw, Save, Search, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog.jsx';
import { StatePanel } from '../../components/ui/StatePanel.jsx';
import { Toolbar } from '../../components/ui/Toolbar.jsx';
import { WorkspaceHeader } from '../../components/ui/WorkspaceHeader.jsx';
import { withSupabaseTokenRetry } from '../../services/supabaseClient.js';
import { CIRCUIT_COUNTS, circuitLayout, cleanCircuits, emptyPanel, normalizePanel, phaseTone } from './panelDirectoryModel.js';

function labelPhase(value) { return value === 'single_phase' ? 'Single Phase' : 'Three Phase'; }
function labelVoltage(value) { return value === '120208' ? '120/208V' : value === '277480' ? '277/480V' : 'Other'; }
function PanelSchedule({ panel, printable = false }) {
  const { starts, claims, invalid } = circuitLayout(panel); const rows = [];
  for (let odd = 1; odd <= panel.circuit_count; odd += 2) rows.push([odd, odd + 1]);
  const side = (number) => {
    const start = claims.get(number); if (start !== number) return null;
    const item = starts.get(number) || { description: '', poles: 1, emergency: false };
    return <><td className={`panel-directory__number ${phaseTone(panel, number)}`}>{number}</td><td rowSpan={item.poles} className={`panel-directory__description${item.emergency ? ' is-emergency' : ''}`}>{item.description || '—'}</td></>;
  };
  return <table className={`panel-directory__schedule${printable ? ' is-printable' : ''}`}><thead><tr><th colSpan="2">Odd circuits</th><th colSpan="2">Even circuits</th></tr></thead><tbody>{rows.map(([odd, even]) => <tr key={odd}>{side(odd)}{side(even)}</tr>)}</tbody>{invalid.size ? <caption>Resolve conflicting circuit assignments before saving or printing.</caption> : null}</table>;
}

function PanelPrint({ panels }) { return <div className={`panel-directory-print-stage ${panels.length === 2 ? 'is-pair' : ''}`}>{panels.map((panel) => <section className="panel-directory-sheet" key={panel.id || panel.designation}><header><img src="/northgate-group-logo.jpg" alt="The Northgate Group" /><div><strong>{panel.designation}</strong><span>{labelPhase(panel.phase_type)} · {labelVoltage(panel.system_voltage)}</span>{panel.panel_location ? <span>{panel.panel_location}</span> : null}</div></header><h1>PANELBOARD</h1><PanelSchedule panel={panel} printable /><footer>Provided Courtesy of The Northgate Group, LLC</footer></section>)}</div>;
}

export function PanelDirectoryWorkspace() {
  const { getToken } = useAuth(); const [rows, setRows] = useState([]); const [panel, setPanel] = useState(emptyPanel); const [search, setSearch] = useState('');
  const [state, setState] = useState({ loading: true, saving: false, error: null, message: '' }); const [dirty, setDirty] = useState(false); const [pending, setPending] = useState(null); const [deleteId, setDeleteId] = useState(null); const [printIds, setPrintIds] = useState([]);
  const layout = useMemo(() => circuitLayout(panel), [panel]);
  const load = async () => { setState((s) => ({ ...s, loading: true, error: null })); try { const result = await withSupabaseTokenRetry(getToken, (client) => client.rpc('list_panel_directories', { p_search: search.trim() || null })); if (result.error) throw result.error; setRows(result.data || []); setState((s) => ({ ...s, loading: false })); } catch (error) { setState((s) => ({ ...s, loading: false, error })); } };
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { const guard = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
  useEffect(() => { const clear = () => document.body.classList.remove('panel-directory-is-printing'); window.addEventListener('afterprint', clear); return () => window.removeEventListener('afterprint', clear); }, []);
  const update = (key, value) => { setPanel((current) => ({ ...current, [key]: value })); setDirty(true); setState((s) => ({ ...s, message: '' })); };
  const updateCircuit = (number, key, value) => { setPanel((current) => { const items = { ...current.circuits.items }; const currentItem = { description: '', poles: 1, emergency: false, ...(items[number] || {}) }; items[number] = { ...currentItem, [key]: value }; return { ...current, circuits: { ...current.circuits, items } }; }); setDirty(true); };
  const open = (value, duplicate = false) => { const next = duplicate ? { ...normalizePanel(value), id: null, designation: `${value.designation} copy` } : normalizePanel(value); const go = () => { setPanel(next); setDirty(Boolean(duplicate)); setPending(null); setState((s) => ({ ...s, message: '' })); }; if (dirty) setPending({ title: 'Discard unsaved panel changes?', description: 'Open another panel without saving the current edits.', go }); else go(); };
  const create = () => open(emptyPanel());
  const save = async () => { if (state.saving || layout.invalid.size) return; setState((s) => ({ ...s, saving: true, error: null, message: '' })); try { const payload = { ...panel, circuits: { schema_version: 1, items: cleanCircuits(panel.circuits.items) } }; const result = await withSupabaseTokenRetry(getToken, (client) => client.rpc('save_panel_directory', { p_id: panel.id || null, p_payload: payload })); if (result.error) throw result.error; setPanel(normalizePanel(result.data)); setDirty(false); setState({ loading: false, saving: false, error: null, message: 'Panel directory saved and audit record recorded.' }); await load(); } catch (error) { setState((s) => ({ ...s, saving: false, error })); } };
  const print = (targets) => { setPrintIds(targets.map((x) => x.id || x.designation)); window.setTimeout(() => { document.body.classList.add('panel-directory-is-printing'); window.print(); }, 0); };
  const printPanels = printIds.map((id) => (id === panel.id || id === panel.designation ? panel : rows.find((row) => row.id === id))).filter(Boolean);
  const remove = async () => { try { const result = await withSupabaseTokenRetry(getToken, (client) => client.rpc('delete_panel_directory', { p_id: deleteId })); if (result.error) throw result.error; if (panel.id === deleteId) { setPanel(emptyPanel()); setDirty(false); } setDeleteId(null); setState((s) => ({ ...s, message: 'Panel directory deleted.' })); await load(); } catch (error) { setDeleteId(null); setState((s) => ({ ...s, error })); } };
  const updateCount = (value) => update('circuit_count', Number(value));
  const numbers = Array.from({ length: panel.circuit_count }, (_, index) => index + 1);
  return <div className="panel-directory-workspace">
    <WorkspaceHeader eyebrow="Add-On Tools" title="Panel Directory" description="Create, maintain, search, and print electrical panel schedules. Job information is optional and remains separate from Jobs." status={<span className="status-pill status-pill--good">Add-on enabled</span>} actions={<><button type="button" className="secondary-button" onClick={load} disabled={state.loading}><RefreshCw /> Refresh</button><button type="button" className="primary-button" onClick={create}><FilePlus2 /> New panel</button></>} />
    <main className="panel-directory__body">
      {state.error ? <StatePanel tone="danger" title="Panel Directory could not be loaded" description={state.error.message} /> : null}{state.message ? <StatePanel tone="success" title="Panel Directory updated" description={state.message} compact /> : null}
      <Toolbar eyebrow="Directory" title="Saved panel schedules" description="Search by designation, job number, project, client, GC, address, or panel location." search={<label className="panel-directory__search"><Search /><span className="sr-only">Search panel directories</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search saved directories" /></label>} />
      <div className="panel-directory__library">{rows.map((row) => <article key={row.id} className={row.id === panel.id ? 'is-current' : ''}><div><strong>{row.designation}</strong><span>{labelPhase(row.phase_type)} · {labelVoltage(row.system_voltage)} · {row.circuit_count} circuits</span><small>{row.project_name || row.job_number || row.client_name || 'No job information'}</small></div><div className="panel-directory__library-actions"><button type="button" onClick={() => open(row)}><FolderOpen /> Open</button><button type="button" onClick={() => open(row, true)}><Copy /> Duplicate</button><button type="button" onClick={() => print([normalizePanel(row)])}><Printer /> Print</button><button type="button" className="is-danger" onClick={() => setDeleteId(row.id)}><Trash2 /> Delete</button></div></article>)}{!state.loading && !rows.length ? <StatePanel tone="neutral" title="No panel directories found" description="Create the first panel directory, or adjust the search." compact /> : null}</div>
      <section className="panel-directory__editor"><div className="panel-directory__editor-header"><div><p className="eyebrow">Panel setup</p><h3>{panel.id ? `Editing ${panel.designation}` : 'New panel directory'}</h3></div><div><button type="button" className="secondary-button" onClick={() => print([panel])} disabled={layout.invalid.size}><Printer /> Print current</button><button type="button" className="primary-button" onClick={save} disabled={state.saving || layout.invalid.size || !panel.designation.trim()}><Save /> {state.saving ? 'Saving…' : 'Save panel'}</button></div></div>
        <div className="panel-directory__form-grid"><label><span>Designation</span><input value={panel.designation} onChange={(e) => update('designation', e.target.value)} maxLength="120" required /></label><label><span>Phase</span><select value={panel.phase_type} onChange={(e) => update('phase_type', e.target.value)}><option value="three_phase">Three Phase</option><option value="single_phase">Single Phase</option></select></label><label><span>System voltage</span><select value={panel.system_voltage} onChange={(e) => update('system_voltage', e.target.value)}><option value="120208">120/208V</option><option value="277480">277/480V</option><option value="other">Other / no standard colors</option></select></label><label><span>Circuits</span><select value={panel.circuit_count} onChange={(e) => updateCount(e.target.value)}>{CIRCUIT_COUNTS.map((count) => <option key={count}>{count}</option>)}</select></label><label className="panel-directory__switch"><input type="checkbox" checked={panel.phase_color_coding} onChange={(e) => update('phase_color_coding', e.target.checked)} /> Color-code circuit numbers by phase and voltage</label></div>
        <details className="panel-directory__job-info"><summary>Optional job information</summary><div className="panel-directory__form-grid"><label><span>Job number</span><input value={panel.job_number} onChange={(e) => update('job_number', e.target.value)} /></label><label><span>Project name</span><input value={panel.project_name} onChange={(e) => update('project_name', e.target.value)} /></label><label><span>Client / GC</span><input value={panel.client_name} onChange={(e) => update('client_name', e.target.value)} /></label><label><span>Panel location</span><input value={panel.panel_location} onChange={(e) => update('panel_location', e.target.value)} /></label><label className="panel-directory__wide"><span>Address</span><input value={panel.project_address} onChange={(e) => update('project_address', e.target.value)} /></label><label className="panel-directory__wide"><span>Notes</span><textarea rows="2" value={panel.notes} onChange={(e) => update('notes', e.target.value)} /></label></div></details>
        <div className="panel-directory__circuit-editor"><table><thead><tr><th colSpan="4">Odd circuits</th><th colSpan="4">Even circuits</th></tr><tr><th>Cir.</th><th>Description</th><th>Poles</th><th>Emergency</th><th>Cir.</th><th>Description</th><th>Poles</th><th>Emergency</th></tr></thead><tbody>{numbers.filter((number) => number % 2).map((odd) => <tr key={odd}>{[odd, odd + 1].map((number) => { const claimedBy = layout.claims.get(number); const hidden = claimedBy && claimedBy !== number; const item = panel.circuits.items[number] || { description: '', poles: 1, emergency: false }; return hidden ? <><td className="panel-directory__circuit-number">{number}</td><td colSpan="3" className="panel-directory__reserved">Reserved by circuit {claimedBy}</td></> : <><td className={`panel-directory__circuit-number ${phaseTone(panel, number)}`}>{number}</td><td><input value={item.description} onChange={(e) => updateCircuit(number, 'description', e.target.value)} placeholder="Description" /></td><td><select value={item.poles} onChange={(e) => updateCircuit(number, 'poles', Number(e.target.value))}><option value="1">1</option><option value="2">2</option>{panel.phase_type === 'three_phase' ? <option value="3">3</option> : null}</select></td><td><input aria-label={`Emergency circuit ${number}`} type="checkbox" checked={Boolean(item.emergency)} onChange={(e) => updateCircuit(number, 'emergency', e.target.checked)} /></td></>; })}</tr>)}</tbody></table><p>Enter a multi-pole load on its first circuit. Following positions on the same side are reserved automatically. Emergency loads print with a yellow description cell and red text.</p>{layout.invalid.size ? <StatePanel compact tone="danger" title="Circuit assignments need attention" description="Multi-pole assignments overlap or extend beyond this panel. Correct them before saving or printing." /> : null}</div>
      </section>
      <section className="panel-directory__preview"><Toolbar eyebrow="Preview" title="Current panel directory" description="The print layout follows the live values above, including unsaved edits." actions={<button type="button" className="secondary-button" onClick={() => print([panel])} disabled={layout.invalid.size}><Printer /> Print current</button>} /><PanelSchedule panel={panel} /></section>
      <section className="panel-directory__composer"><Toolbar eyebrow="Print composer" title="Print one or two saved panels" description="Select up to two saved panels for a compact side-by-side letter print." /><div><select value={printIds[0] || ''} onChange={(e) => setPrintIds([e.target.value, printIds[1]].filter(Boolean))}><option value="">First saved panel</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.designation}</option>)}</select><select value={printIds[1] || ''} onChange={(e) => setPrintIds([printIds[0], e.target.value].filter(Boolean))}><option value="">Second panel (optional)</option>{rows.filter((row) => row.id !== printIds[0]).map((row) => <option key={row.id} value={row.id}>{row.designation}</option>)}</select><button type="button" className="primary-button" disabled={!printIds.length} onClick={() => print(printPanels)}><Printer /> Print selection</button></div></section>
    </main><PanelPrint panels={printPanels} />
    <ConfirmDialog open={Boolean(pending)} onCancel={() => setPending(null)} onConfirm={() => pending?.go()} title={pending?.title || ''} description={pending?.description || ''} confirmLabel="Discard changes" tone="danger" />
    <ConfirmDialog open={Boolean(deleteId)} onCancel={() => setDeleteId(null)} onConfirm={remove} title="Delete panel directory?" description="This removes the saved directory. The deletion is recorded in the audit log." confirmLabel="Delete panel" tone="danger" />
  </div>;
}
