import {useAuth,useUser} from '@clerk/clerk-react';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {afcApi} from './afcApi.js';
import {blankStudy,addNode,reparent,importStudy,studyResults,incomingSegment,id,KINDS,FAULTS,comparison} from './model.mjs';
import {sizes,descendants,cValue} from './engine.mjs';
import {downloadBlob} from '../electrical-inspections/inspectionApi.js';
import './afc.css';
// Unsaved drafts survive in-app navigation, scoped to this signed-in account.
// They are never a replacement for shared persistence.
const pending=new Map();
function Field({label,value,onChange,type='text',options,disabled=false}){
 return <label className="afc-field"><span>{label}</span>{options?<select aria-label={label} value={value??''} disabled={disabled} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select>:<input aria-label={label} type={type} value={value??''} disabled={disabled} onChange={e=>onChange(e.target.value)} step={type==='number'?'any':undefined}/>}</label>;
}
const choice=(value,label)=>({value,label});
function RunEditor({value,onChange,onRemove,index}){
 const set=(key,v)=>onChange({...value,[key]:v}),neutral=value.neutral||{mode:'none'};
 return <fieldset className="afc-run"><legend>Incoming segment {index+1}</legend><div className="afc-grid">
  <Field label="One-way length (ft)" type="number" value={value.length} onChange={v=>set('length',v)}/>
  <Field label="Identical parallel sets" type="number" value={value.sets} onChange={v=>set('sets',v)}/>
  <Field label="Conductor data" value={value.mode} onChange={v=>set('mode',v)} options={[choice('table','600 V table preset'),choice('custom','Custom C value')]}/>
  {value.mode==='custom'?<><Field label="Custom C" type="number" value={value.c} onChange={v=>set('c',v)}/><Field label="Impedance / configuration reference" value={value.reference} onChange={v=>set('reference',v)}/></>:<>
   <Field label="Conductor size" value={value.size} onChange={v=>set('size',v)} options={sizes}/>
   <Field label="Material" value={value.material} onChange={v=>set('material',v)} options={['Cu','Al']}/>
   <Field label="Raceway" value={value.raceway} onChange={v=>set('raceway',v)} options={[choice('steel','Steel'),choice('pvc','Nonmagnetic')]}/>
  </>}
  <Field label="L–N neutral path" value={neutral.mode} onChange={v=>set('neutral',{...neutral,mode:v})} options={[choice('none','Not modeled'),choice('same','Same conductor and sets as phase'),choice('custom','Custom neutral')]}/>
  {neutral.mode==='custom'&&<><Field label="Neutral C" type="number" value={neutral.c} onChange={v=>set('neutral',{...neutral,c:v})}/><Field label="Parallel neutral sets" type="number" value={neutral.sets} onChange={v=>set('neutral',{...neutral,sets:v})}/><Field label="Neutral reference" value={neutral.reference} onChange={v=>set('neutral',{...neutral,reference:v})}/></>}
 </div><small>Preset C: {cValue(value)??'Choose conductor'} • 600 V, three single conductors, Eaton 2014 Table 4.</small><button type="button" onClick={onRemove}>Remove segment</button></fieldset>;
}
export function AfcWorkspace({permissions}){
 const {getToken}=useAuth(),{user}=useUser(),location=useLocation(),api=useMemo(()=>afcApi(getToken),[getToken]);
 const account=user?.id||permissions?.userId||'signed-out',cache=pending.get(account);
 const [record,setRecord]=useState(cache?.record||null),[document,setDocument]=useState(cache?.document||null),[job,setJob]=useState(cache?.job||''),[original,setOriginal]=useState(cache?.original||null),[dirty,setDirty]=useState(Boolean(cache));
 const [list,setList]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[tab,setTab]=useState('equipment'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[jobs,setJobs]=useState([]),[jobSearch,setJobSearch]=useState(''),[note,setNote]=useState(''),[selectedLabels,setSelectedLabels]=useState([]),[offset,setOffset]=useState(0);
 const sequence=useRef(0),lastAccount=useRef(account),fileInput=useRef();
 const result=useMemo(()=>document?studyResults(document):null,[document]);
 const node=document?.nodes.find(n=>n.id===selected)||document?.nodes[0],recordJob=location.state?.jobId||new URLSearchParams(location.search).get('job');
 useEffect(()=>{if(lastAccount.current!==account){pending.clear();lastAccount.current=account;setDocument(null);setRecord(null);setDirty(false);}return()=>{};},[account]);
 useEffect(()=>{if(dirty&&document)pending.set(account,{record,document,job,original});else pending.delete(account);},[account,dirty,document,record,job,original]);
 useEffect(()=>{const handler=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 const run=async fn=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message||String(e));}finally{setBusy(false);}};
 const refresh=async()=>{const seq=++sequence.current,rows=await api.rpc('afc_read',{p_search:search,p_job:recordJob||null,p_offset:offset});if(sequence.current===seq)setList(rows);};
 useEffect(()=>{let current=true;const seq=++sequence.current;api.rpc('afc_read',{p_search:search,p_job:recordJob||null,p_offset:offset}).then(rows=>{if(current&&seq===sequence.current)setList(rows);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[api,search,recordJob,offset,account]);
 useEffect(()=>{let current=true;api.rpc('afc_jobs',{p_search:jobSearch}).then(rows=>{if(current)setJobs(rows);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[api,jobSearch,account]);
 const canLeave=()=>!dirty||window.confirm('Discard the unsaved changes to this study?');
 const open=async studyId=>{if(!canLeave())return;await run(async()=>{const row=await api.rpc('afc_read',{p_id:studyId});setRecord(row);setDocument(row.document);setJob(row.job_id||'');setOriginal(row.original_import);setDirty(false);setSelected(row.document.nodes[0].id);setNote('');setSelectedLabels([]);});};
 const update=fn=>{setDocument(d=>{const next=structuredClone(d);fn(next);return next;});setDirty(true);};
 const changeNode=(key,value)=>update(d=>{d.nodes.find(n=>n.id===node.id)[key]=value;});
 const newStudy=()=>{if(!canLeave())return;const d=blankStudy();d.preparedBy=user?.fullName||'';setRecord(null);setDocument(d);setJob(recordJob||'');setOriginal(null);setSelected(d.nodes[0].id);setSelectedLabels([]);setDirty(true);setError('');};
 const save=async()=>{const row=await api.rpc('afc_save',{p_request:id(),p_id:record?.id||null,p_version:record?.version||null,p_document:document,p_division:record?.division||permissions?.department||'Electrical',p_job:job||null,p_import:original});setRecord({...row,revisions:record?.revisions||[],can_review:record?.can_review});setDirty(false);setMessage('Study saved as a shared draft.');await refresh();return row;};
 const exportPdf=async(kind,ids=null)=>{const {afcPdf}=await import('../../../supabase/functions/_shared/afc/pdf.mjs');const bytes=await afcPdf({document,results:result,kind,nodeIds:ids});downloadBlob(new Blob([bytes],{type:'application/pdf'}),'AFC-draft-'+kind+'.pdf');};
 const file=async entry=>{const blob=await api.download(entry.storage_path);downloadBlob(blob,entry.file_name);};
 const options=document?.nodes.map(n=>choice(n.id,n.name||'Unnamed equipment'))||[];
 const layer=(key,rows)=>update(d=>{d.layers??={};d.layers[key]=rows;});
 const modifyLayer=(key,rowId,field,value)=>layer(key,document.layers[key].map(x=>x.id===rowId?{...x,[field]:value}:x));
 return <main className="afc-workspace">
 <header className="afc-heading"><div><p className="afc-eyebrow">ADD-ON TOOLS</p><h1>Available Fault Current</h1><p>Build a radial study, compare entered equipment ratings, and preserve reviewed reports.</p></div><button onClick={newStudy} disabled={busy}>New study</button></header>
 {error&&<div role="alert" className="afc-error">{error}</div>}{message&&<div role="status">{message}</div>}
 <div className="afc-layout"><aside className="afc-directory"><Field label="Find a study" value={search} onChange={v=>{setSearch(v);setOffset(0);}}/>
 <button disabled={busy} onClick={()=>run(refresh)}>Refresh studies</button>{list.length===0&&<p>No studies found.</p>}{list.map(s=><button className={record?.id===s.id?'is-selected':''} key={s.id} onClick={()=>open(s.id)} disabled={busy}><strong>{s.title||'Untitled study'}</strong><small>{s.location||'Location not entered'} · {s.status}</small></button>)}
 <div className="afc-actions"><button disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={list.length<50||busy} onClick={()=>setOffset(offset+50)}>Next</button></div>
 </aside><section className="afc-editor" inert={busy?true:undefined}>{!document?<div className="afc-card"><h2>Open a study or start a new one</h2><p>Drafts can be incomplete. Review and release require complete source data and a designated reviewer.</p><button onClick={()=>fileInput.current.click()}>Import study backup</button></div>:<>
 <div className="afc-actions"><strong>{record?.status==='reviewed'?'Reviewed study':record?'Shared draft':'Unsaved draft'}{dirty?' · Unsaved changes':''}</strong><button disabled={busy} onClick={()=>run(save)}>Save draft</button><button disabled={busy} onClick={()=>fileInput.current.click()}>Import backup</button><button onClick={()=>downloadBlob(new Blob([JSON.stringify({document,original},null,2)],{type:'application/json'}),'AFC-study-backup.json')}>Export backup</button></div>
 <p className="afc-help">Required inputs apply to release. Blank optional layers mean “not modeled.” Editing and saving a reviewed study creates a new draft and preserves earlier reports.</p>
 <div className="afc-grid"><Field label="Study title" value={document.title} onChange={v=>update(d=>{d.title=v;})}/><Field label="Location / study reference" value={document.reference} onChange={v=>update(d=>{d.reference=v;})}/><Field label="Prepared by" value={document.preparedBy} onChange={v=>update(d=>{d.preparedBy=v;})}/><Field label="Calculation date" type="date" value={document.date} onChange={v=>update(d=>{d.date=v;})}/><Field label="Find job or service call" value={jobSearch} onChange={setJobSearch}/><Field label="Attached job / service call" value={job} onChange={v=>{setJob(v);setDirty(true);}} options={[choice('','Standalone'),...(!jobs.some(j=>j.id===job)&&job?[choice(job,'Current linked record')]:[]),...jobs.map(j=>choice(j.id,(j.number||'')+' · '+j.name))]}/></div>
 <nav className="afc-tabs" aria-label="Study sections">{[['equipment','Equipment & feeders'],['layers','Optional cases'],['results','Results & map'],['release','Review & archive']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==='equipment'&&<div className="afc-equipment"><aside>{document.nodes.map(n=><button key={n.id} aria-pressed={node.id===n.id} onClick={()=>setSelected(n.id)}>{n.name||'Unnamed'}<small>{n.fault||'Fault not named'}</small></button>)}<Field label="New equipment type" value="" onChange={kind=>{if(kind){const next=addNode(document,node.id,kind);setDocument(next);setSelected(next.nodes.at(-1).id);setDirty(true);}}} options={[choice('','Add below selected…'),...KINDS.filter(k=>k!=='source')]}/></aside><section className="afc-card"><h2>{node.name||'Equipment'}</h2><div className="afc-grid">
 <Field label="Equipment name" value={node.name} onChange={v=>changeNode('name',v)}/><Field label="Fault name" value={node.fault} onChange={v=>changeNode('fault',v)}/><Field label="Nameplate rating (kA)" type="number" value={node.rating} onChange={v=>changeNode('rating',v)}/>
 {node.kind!=='source'&&<Field label="Fed from" value={node.parent} options={options.filter(o=>!descendants(document.nodes,node.id).has(o.value))} onChange={v=>{setDocument(reparent(document,node.id,v));setDirty(true);}}/>}
 {node.kind==='source'&&<><Field label="Source method" value={node.method} onChange={v=>changeNode('method',v)} options={[choice('known','Utility-provided current'),choice('transformer','Infinite-primary transformer')]}/><Field label="Phase" value={node.phase} onChange={v=>changeNode('phase',+v)} options={[choice(3,'Three phase'),choice(1,'Single phase L–L')]}/>{node.method==='known'&&<Field label="Available source current (A)" type="number" value={node.known} onChange={v=>changeNode('known',v)}/>}</>}
 {(node.kind==='source'||node.kind==='transformer')&&<><Field label={node.kind==='transformer'?'Secondary voltage (V L–L)':'Source voltage (V L–L)'} type="number" value={node.voltage} onChange={v=>changeNode('voltage',v)}/><Field label="Utility / nameplate reference" value={node.sourceReference} onChange={v=>changeNode('sourceReference',v)}/>{(node.kind==='transformer'||node.method==='transformer')&&<><Field label="Transformer kVA" type="number" value={node.kva} onChange={v=>changeNode('kva',v)}/><Field label="Nameplate impedance (%)" type="number" value={node.z} onChange={v=>changeNode('z',v)}/><Field label="Impedance reduction (%)" type="number" value={node.tolerance} onChange={v=>changeNode('tolerance',v)}/></>}</>}
 </div>
 {(node.segments||[]).map((s,index)=><RunEditor key={s.id} value={s} index={index} onChange={v=>changeNode('segments',node.segments.map(x=>x.id===s.id?v:x))} onRemove={()=>changeNode('segments',node.segments.filter(x=>x.id!==s.id))}/>)}
 {node.kind!=='source'&&<div className="afc-actions"><button onClick={()=>changeNode('segments',[...node.segments,incomingSegment()])}>Add incoming segment</button><button onClick={()=>{if(window.confirm('Remove this equipment and its downstream branch?'))update(d=>{const ids=descendants(d.nodes,node.id);d.nodes=d.nodes.filter(n=>!ids.has(n.id));setSelected(d.nodes[0].id);});}}>Remove branch</button></div>}
 {(node.kind==='source'||node.kind==='transformer')&&<fieldset><legend>Optional L–N source</legend><div className="afc-grid"><Field label="L–N source method" value={node.ln?.mode||'none'} onChange={v=>changeNode('ln',{...node.ln,mode:v})} options={[choice('none','Not modeled'),choice('known','Known secondary L–N current'),...(node.kind==='source'&&node.phase===1&&node.method==='transformer'?[choice('center','Center-tap 1.5× approximation')]:[])]}/>{node.ln?.mode==='known'&&['current','voltage','reference'].map(k=><Field key={k} label={'L–N '+k} type={k==='reference'?'text':'number'} value={node.ln[k]} onChange={v=>changeNode('ln',{...node.ln,[k]:v})}/>)}</div></fieldset>}
 <fieldset><legend>External engineering results</legend><p>Keep the source study reference. These values are entered results, not locally calculated faults.</p>{(node.external||[]).map(e=><div className="afc-grid afc-run" key={e.id}><Field label="External case name" value={e.caseName} onChange={v=>changeNode('external',node.external.map(x=>x.id===e.id?{...x,caseName:v}:x))}/>{['amps','reference'].map(k=><Field key={k} label={k==='amps'?'External RMS current (A)':'External study reference'} type={k==='amps'?'number':'text'} value={e[k]} onChange={v=>changeNode('external',node.external.map(x=>x.id===e.id?{...x,[k]:v}:x))}/>)}<Field label="External fault type" value={e.fault} options={FAULTS} onChange={v=>changeNode('external',node.external.map(x=>x.id===e.id?{...x,fault:v}:x))}/><button onClick={()=>changeNode('external',node.external.filter(x=>x.id!==e.id))}>Remove external result</button></div>)}<button onClick={()=>changeNode('external',[...(node.external||[]),{id:id(),caseName:'',amps:'',reference:'',fault:'L–G'}])}>Add external result</button></fieldset>
 </section></div>}
 {tab==='layers'&&<div className="afc-card"><h2>Optional operating cases</h2><p>Generator cases model open transfer only. No source paralleling, backfeed, inverter pool, or motor network solution is implied.</p>
 <h3>Generators</h3>{(document.layers?.generators||[]).map(g=><fieldset key={g.id}><legend>{g.name||'Generator'}</legend><div className="afc-grid">{['name','reference'].map(k=><Field key={k} label={'Generator '+k} value={g[k]} onChange={v=>modifyLayer('generators',g.id,k,v)}/>)}<Field label="Generator connection point" value={g.bus} options={[choice('','Choose equipment'),...options]} onChange={v=>modifyLayer('generators',g.id,'bus',v)}/><Field label="Generator source method" value={g.method} options={[choice('known','Manufacturer initial symmetrical A'),choice('reactance','Alternator kVA / X″d')]} onChange={v=>modifyLayer('generators',g.id,'method',v)}/>{(g.method==='known'?['known']:['kva','xd']).map(k=><Field key={k} label={{known:'Generator terminal current (A)',kva:'Alternator kVA',xd:'Subtransient X″d (%)'}[k]} type="number" value={g[k]} onChange={v=>modifyLayer('generators',g.id,k,v)}/>)}{['lnCurrent','lnVoltage'].map(k=><Field key={k} label={k==='lnCurrent'?'Generator L–N current (A)':'Generator L–N voltage (V)'} type="number" value={g[k]} onChange={v=>modifyLayer('generators',g.id,k,v)}/>)}</div><h4>Independent generator feeder</h4><div className="afc-grid">{['length','c','sets','neutralC','neutralSets','reference'].map(k=><Field key={k} label={{length:'Generator feeder length (ft)',c:'Generator feeder C',sets:'Generator parallel sets',neutralC:'Generator neutral C',neutralSets:'Generator neutral sets',reference:'Generator feeder configuration reference'}[k]} type={k==='reference'?'text':'number'} value={g.feeder?.[k]} onChange={v=>modifyLayer('generators',g.id,'feeder',{...g.feeder,[k]:v})}/>)}</div><button onClick={()=>layer('generators',document.layers.generators.filter(x=>x.id!==g.id))}>Remove generator</button></fieldset>)}
 <button onClick={()=>layer('generators',[...(document.layers?.generators||[]),{id:id(),name:'',reference:'',bus:'',method:'known',known:'',kva:'',xd:'',lnCurrent:'',lnVoltage:'',feeder:{length:'',c:'',sets:1,neutralC:'',neutralSets:1,reference:''}}])}>Add generator case</button>
 <h3>Induction-motor screening</h3><p>Running FLA × editable multiplier, referred by voltage to each energized fault. No attenuation or decay. Exclude VFD and inverter-fed motors.</p>{(document.layers?.motors||[]).map(m=><fieldset key={m.id}><legend>{m.name||'Motor group'}</legend><div className="afc-grid">{['name','fla','multiplier','reference'].map(k=><Field key={k} label={{name:'Motor group name',fla:'Running motor FLA',multiplier:'Screening multiplier',reference:'Motor data reference'}[k]} type={['fla','multiplier'].includes(k)?'number':'text'} value={m[k]} onChange={v=>modifyLayer('motors',m.id,k,v)}/>)}<Field label="Motor bus" value={m.bus} options={[choice('','Choose equipment'),...options]} onChange={v=>modifyLayer('motors',m.id,'bus',v)}/><Field label="Motor operating cases" value={m.operation} options={['both','utility','generator']} onChange={v=>modifyLayer('motors',m.id,'operation',v)}/></div><button onClick={()=>layer('motors',document.layers.motors.filter(x=>x.id!==m.id))}>Remove motor group</button></fieldset>)}<button onClick={()=>layer('motors',[...(document.layers?.motors||[]),{id:id(),name:'',reference:'',bus:'',fla:'',multiplier:4,operation:'both'}])}>Add motor group</button></div>}
 {tab==='results'&&<div className="afc-card"><h2>Results & system map</h2><p>Highest entered/modeled cases are an envelope; different nodes may have different highest cases. A numeric comparison does not approve equipment suitability.</p>{document.nodes.map(n=><div className="afc-result" key={n.id}><h3>{n.name} / {n.fault}</h3><p>{document.nodes.find(p=>p.id===n.parent)?.name||'Utility'} → {n.name}</p><p>{comparison(n,result.byNode[n.id]).label}</p>{result.base[n.id]?.error?<p>{result.base[n.id].error}</p>:<><strong>{result.byNode[n.id]?.maximum?Math.ceil(result.byNode[n.id].maximum.amps).toLocaleString()+' A RMS symmetrical':'Not calculated'}</strong>{result.byNode[n.id]?.rows.map((r,i)=><p key={i}>{r.caseName} · {r.fault} · {Math.ceil(r.amps).toLocaleString()} A · {r.basis}</p>)}<details><summary>Calculation details</summary><pre>{JSON.stringify(result.base[n.id],null,2)}</pre></details></>}</div>)}{result.notes.map(n=><p key={n}>{n}</p>)}</div>}
 {tab==='release'&&<div className="afc-card"><h2>Review & archive</h2><p>Confirm source data, applicable faults, modeling assumptions, equipment ratings, and the intended use before release. These are fault-current labels, separate from arc-flash labels.</p><Field label="Label size (inches)" value={document.labelSize||'4x3'} options={['4x3','6x4']} onChange={v=>update(d=>{d.labelSize=v;})}/>
 {result.errors.length?<div className="afc-error"><h3>Complete before generating new outputs</h3><ul>{result.errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>:<p>Calculation inputs are complete. Reviewer judgment is still required.</p>}
 <div className="afc-actions"><button disabled={busy||result.errors.length>0} onClick={()=>run(()=>exportPdf('report'))}>Download draft report</button><button disabled={busy||result.errors.length>0||!selectedLabels.length} onClick={()=>run(()=>exportPdf('labels',selectedLabels))}>Download selected draft labels</button></div>
 <fieldset><legend>Equipment labels</legend><button onClick={()=>setSelectedLabels(document.nodes.map(n=>n.id))}>Select all</button><button onClick={()=>setSelectedLabels([])}>Clear selection</button>{document.nodes.map(n=><label className="afc-check" key={n.id}><input type="checkbox" checked={selectedLabels.includes(n.id)} onChange={e=>setSelectedLabels(e.target.checked?[...selectedLabels,n.id]:selectedLabels.filter(x=>x!==n.id))}/>{n.name} / {n.fault}</label>)}</fieldset>
 {(record?.can_review||permissions?.permissions?.can_review_afc_studies)&&<><label className="afc-field"><span>Reviewed scope and assumptions</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label><button disabled={busy||dirty||!record||record.status!=='draft'||result.errors.length>0||!note.trim()} onClick={()=>run(async()=>{await api.release({id:record.id,version:record.version,requestId:id(),note});const updated=await api.rpc('afc_read',{p_id:record.id});setRecord(updated);setMessage('Reviewed revision and original files archived.');await refresh();})}>Review and release report & labels</button><p>Save the draft before release. The server recalculates and verifies each archived file.</p></>}
 <h3>Released revisions</h3>{!record?.revisions?.length&&<p>No released revisions.</p>}{record?.revisions?.map(r=><details key={r.id}><summary>Revision {r.revision} · {r.superseded?'Superseded':'Reviewed'} · {r.reviewer_name}</summary><p>{r.reviewed_at} · {r.review_note}</p>{r.files.map(f=><button key={f.id} onClick={()=>run(()=>file(f))} disabled={busy}>Download original {f.kind==='label'?r.document.nodes.find(n=>n.id===f.node_id)?.name||f.node_id:f.kind}</button>)}</details>)}
 </div>}
 </>}</section></div>
 <input ref={fileInput} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files[0];e.target.value='';if(!f||!canLeave())return;run(async()=>{if(f.size>1500000)throw Error('Choose a study backup under 1.5 MB.');const imported=importStudy(JSON.parse(await f.text()));setDocument(imported.document);setOriginal(imported.original);setRecord(null);setJob('');setSelected(imported.document.nodes[0].id);setDirty(true);setMessage('Imported into a new unsaved study. Original source is retained.');});}}/>
 </main>;
}
