import {PGlite} from '../.temp/inspection-checks/node_modules/@electric-sql/pglite/dist/index.js';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {demo} from '../src/modules/afc/engine.mjs';
import {importStudy,studyResults} from '../src/modules/afc/model.mjs';
import {verifyDocumentTags} from './check-document-tags-db.mjs';
const db=new PGlite();let checks=0;
const query=(sql,args=[])=>db.query(sql,args),one=async(sql,args=[])=>Object.values((await query(sql,args)).rows[0])[0];
const actor=async name=>{await db.exec('reset role');await query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:name,role:'authenticated'})]);await db.exec('set role authenticated');};
const denied=async(fn,re)=>{await assert.rejects(fn,re);checks++;};
try{
 await db.exec(await readFile('tests/fixtures/inspectionPrerequisites.sql','utf8'));
 await db.exec("create role service_role; create or replace function auth.jwt()returns jsonb language sql as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$");
 await db.exec('set check_function_bodies=off');await db.exec(await readFile('tests/fixtures/inspectionAuthFunctions.sql','utf8'));await db.exec('set check_function_bodies=on');
 for(const f of ['20260912134038_document_edit_restore.sql','20260914235450_electrical_inspection_workflow.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 await db.exec(await readFile('tests/fixtures/inspectionPermissionManagement.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20260915000120_inspection_reviewer_permission_management.sql','utf8'));
 // Production has an explicit correction capability outside role defaults.
 const priorCheck=await one("select pg_get_expr(conbin,conrelid) from pg_constraint where conrelid='user_permission_overrides'::regclass and conname='user_permission_overrides_permission_flag_check'");
 await db.exec("alter table user_permission_overrides drop constraint user_permission_overrides_permission_flag_check;alter table user_permission_overrides add constraint user_permission_overrides_permission_flag_check check(("+priorCheck+") or permission_flag='can_developer_data_correction');insert into user_permissions(clerk_user_id,role,division)values('retained-override-fixture','Developer','Electrical');insert into user_permission_overrides(user_id,permission_flag,granted)values('retained-override-fixture','can_developer_data_correction',true)");
 for(const f of ['20260916103702_afc_shared_studies.sql','20260916103706_document_sections.sql','20260916103711_northgate_read_tools_audit.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 assert.equal(await one("select granted from user_permission_overrides where user_id='retained-override-fixture' and permission_flag='can_developer_data_correction'"),true);checks++;
 await db.exec("insert into user_permissions(clerk_user_id,role,division,display_name)values('tech','User','Electrical','Tech'),('other','User','Electrical','Other'),('reviewer','Manager','Electrical','Reviewer'),('outside','User','Construction','Outside'),('inactive','Developer','Electrical','Inactive');update user_permissions set is_active=false where clerk_user_id='inactive';insert into tool_addon_access values('available_fault_current','tech',true),('available_fault_current','reviewer',true),('available_fault_current','other',true),('available_fault_current','outside',true);insert into user_permission_overrides(user_id,permission_flag,granted)values('reviewer','can_review_afc_studies',true);");
 await db.exec('CREATE TRIGGER guard_document_audit_mutation BEFORE INSERT OR UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.guard_document_audit_mutation()');
 const job=await one("insert into jobs(name,job_number,division)values('Synthetic Job','TEST-AFC','Electrical')returning id");
 const document=importStudy(demo()).document;document.preparedBy='Synthetic preparer';
 const save=(id=null,version=null,request=crypto.randomUUID(),jobId=null)=>one('select afc_save($1,$2,$3,$4,$5,$6)',[request,id,version,document,'Electrical',jobId]);
 await actor('tech');let saved=await save();assert.equal(saved.version,1);checks++;
 const request=crypto.randomUUID();saved=await save(saved.id,saved.version,request);assert.deepEqual(await save(saved.id,1,request),saved);checks++;
 await denied(()=>save(saved.id,1),/changed/);
 await denied(()=>save(saved.id,saved.version,crypto.randomUUID(),job),/management authority/);
 await actor('other');assert.deepEqual(await one('select afc_read()'),[]);await denied(()=>one('select afc_read($1)',[saved.id]),/unavailable/);
 await actor('outside');await denied(()=>one('select afc_read($1)',[saved.id]),/unavailable/);
 await actor('inactive');await denied(()=>save(),/Active sign-in/);
 await actor('tech');await denied(()=>one('select afc_release_context($1,$2,$3)',[saved.id,saved.version,crypto.randomUUID()]),/reviewer authority/);
 await denied(()=>query('update afc_studies set document=$1 where id=$2',[document,saved.id]),/permission denied/);
 await actor('reviewer');saved=await save(saved.id,saved.version,crypto.randomUUID(),job);
 const releaseId=crypto.randomUUID(),context=await one('select afc_release_context($1,$2,$3)',[saved.id,saved.version,releaseId]);
 const results=studyResults(context.document);results.releaseContext={reviewerName:context.reviewer_name,jobSnapshot:context.job_snapshot,reviewedAt:context.reviewed_at};assert.deepEqual(results.errors,[]);
 const files=['report','labels','source'].map(kind=>({id:crypto.randomUUID(),kind,file_name:kind+'.pdf',storage_path:'afc/'+saved.id+'/'+releaseId+'/'+crypto.randomUUID()+'/'+kind,size:20,sha256:'a'.repeat(64)}));
 const finish=()=>one('select afc_finalize_release($1,$2,$3,$4,$5,$6,$7,$8)',['reviewer',saved.id,saved.version,releaseId,results,files,'Synthetic reviewed scope',context.reviewed_at]);
 await denied(finish,/permission denied/);
 await db.exec('reset role;set role service_role');await denied(finish,/file is missing/);
 await db.exec('reset role');assert.equal(await one('select count(*)::int from afc_revisions'),0);checks++;
 for(const f of files)await query('insert into storage.objects(bucket_id,name,metadata)values($1,$2,$3)',['northgate-files',f.storage_path,{size:20}]);
 await db.exec('set role service_role');const issued=await finish();assert.equal(issued.status,'reviewed');assert.deepEqual(await finish(),issued);checks+=2;
 await actor('other');assert.equal((await query('select id from documents where id=$1',[files[0].id])).rows.length,1);assert.equal((await query('select name from storage.objects where name=$1',[files[0].storage_path])).rows.length,1);checks+=2;
 await denied(()=>one('select afc_read($1)',[saved.id]),/unavailable/);
 await actor('reviewer');await denied(async()=>one('select maintain_owner_document($1,$2,$3,$4,$5,$6,$7)',[files[0].id,'job',job,'edit',{file_name:'changed.pdf',document_type:'misc'},'Attempt overwrite',await one('select updated_at from documents where id=$1',[files[0].id])]),/immutable/);
 const before=await one('select afc_read($1)',[saved.id]);document.title='Revised synthetic study';saved=await save(saved.id,issued.version,crypto.randomUUID(),null);assert.equal(saved.status,'draft');assert.deepEqual((await one('select afc_read($1)',[saved.id])).revisions,before.revisions);checks+=2;
 await actor('other');assert.equal((await query('select id from documents where id=$1',[files[0].id])).rows.length,1);checks++;
 await db.exec("reset role;update user_permission_overrides set granted=false where user_id='reviewer' and permission_flag='can_review_afc_studies'");
 await actor('reviewer');await denied(()=>one('select afc_release_context($1,$2,$3)',[saved.id,saved.version,crypto.randomUUID()]),/reviewer authority/);
 await db.exec('reset role');assert.equal(await one("select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and left(p.proname,4)='afc_' and has_function_privilege('anon',p.oid,'EXECUTE')"),0);checks++;
 assert.equal(await one("select has_function_privilege('authenticated','public.afc_finalize_release(text,uuid,integer,uuid,jsonb,jsonb,text,timestamptz)','EXECUTE')"),false);checks++;
 await actor('reviewer');
 const plain=await one("insert into documents(division,owner_type,owner_id,storage_path,file_name,document_type,created_by)values('Electrical','job',$1,$2,'plans.pdf','plans','reviewer')returning to_jsonb(documents)",[job,'documents/job/'+job+'/plans.pdf']);
 assert.equal(plain.document_section,null);checks++;
 const classified=await one('select to_jsonb(set_document_section($1,$2,$3))',[plain.id,'construction',plain.updated_at]);assert.equal(classified.document_section,'construction');checks++;
 await denied(()=>one('select set_document_section($1,$2,$3)',[plain.id,'general',plain.updated_at]),/changed/);
 await denied(()=>query("update documents set document_section='general' where id=$1",[plain.id]),/section workflow/);
 await denied(async()=>one('select set_document_section($1,$2,$3)',[files[0].id,'general',await one('select updated_at from documents where id=$1',[files[0].id])]),/source workflow/);
 assert.equal(await one('select document_section from documents where id=$1',[files[0].id]),'electrical');checks++;
 const auditId=crypto.randomUUID();await one('select northgate_audit_read($1,$2,$3,$4)',[auditId,'get_job_summary',{id:job},'started']);await one('select northgate_audit_read($1,$2,$3,$4)',[auditId,'get_job_summary',{id:job},'succeeded']);checks++;
 await denied(()=>one('select northgate_audit_read($1,$2,$3,$4)',[crypto.randomUUID(),'run_sql',{sql:'select 1'},'started']),/Invalid read-tool/);
 await actor('other');await denied(()=>one('select set_document_section($1,$2,$3)',[plain.id,'general',classified.updated_at]),/management authority/);
 assert.equal((await query('select * from northgate_tool_reads')).rows.length,0);checks++;
 await actor('inactive');await denied(()=>one('select northgate_read_context()'),/Active sign-in/);
 await db.exec("reset role;insert into user_permissions(clerk_user_id,role,division,display_name)values('developer','Developer','Electrical','Developer')");
 await actor('developer');assert.equal((await one('select northgate_read_context()')).permissions.can_review_afc_studies,false);checks++;
 await one('select save_user_permission_template($1,NULL,$2,$3,$4)',['developer',{can_review_afc_studies:true},{template_id:null,overrides:{}},'Synthetic AFC reviewer grant']);
 assert.equal((await one('select northgate_read_context()')).permissions.can_review_afc_studies,true);checks++;
 await denied(()=>one('select save_user_permission_template($1,NULL,$2,$3,$4)',['developer',{can_review_afc_studies:true,can_manage_jobs:false},{template_id:null,overrides:{can_review_afc_studies:true}},'Unrelated override']),/Only inspection and AFC/);
 const invalid=structuredClone(document);invalid.nodes[0].name={invalid:true};await denied(()=>one('select afc_save($1,NULL,NULL,$2) ',[crypto.randomUUID(),invalid]),/equipment text/);
 console.log('PASS: '+checks+' AFC database authorization, shared drafts, stale saves, replay, release rollback, file protection and historical attachment checks.');
 await verifyDocumentTags(db);
}catch(e){console.error('AFC DB check failed:',e.message,e.detail||'',e.where||'',e.position||'',e.query?.slice(Math.max(0,Number(e.position)-160),Number(e.position)+120)||'');process.exitCode=1;}finally{await db.close();}
