-- change_logs only accepts the established audit actions. Catalogue-specific
-- detail remains in table_name and after_data rather than inventing actions.
CREATE OR REPLACE FUNCTION public.apply_financial_catalogue_to_job(p_job_id UUID,p_catalogue_ids UUID[],p_reason TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor_id TEXT := auth.jwt() ->> 'sub'; actor_name TEXT; target_job public.jobs%ROWTYPE; catalog public.financial_line_catalogue%ROWTYPE; project_division public.job_budget_divisions%ROWTYPE; existing_line public.job_budget_lines%ROWTYPE; added_count INTEGER := 0; aligned_count INTEGER := 0; division_count INTEGER := 0;
BEGIN
 IF actor_id IS NULL THEN RAISE EXCEPTION 'authenticated Clerk JWT is required' USING ERRCODE='28000'; END IF;
 IF p_job_id IS NULL OR COALESCE(array_length(p_catalogue_ids,1),0)=0 OR NULLIF(BTRIM(COALESCE(p_reason,'')),'') IS NULL THEN RAISE EXCEPTION 'job, at least one catalogue line, and an audit reason are required'; END IF;
 IF NOT public.current_user_can_edit_job(p_job_id,'can_approve_budget') THEN RAISE EXCEPTION 'can_approve_budget is required' USING ERRCODE='42501'; END IF;
 SELECT * INTO target_job FROM public.jobs WHERE id=p_job_id AND archived_at IS NULL FOR UPDATE; IF target_job.id IS NULL THEN RAISE EXCEPTION 'active job not found'; END IF;
 SELECT COALESCE(NULLIF(display_name,''),NULLIF(email,''),actor_id) INTO actor_name FROM public.user_permissions WHERE clerk_user_id=actor_id LIMIT 1;
 FOR catalog IN SELECT * FROM public.financial_line_catalogue WHERE id=ANY(p_catalogue_ids) AND is_active ORDER BY division_code,sort_order,cost_code LOOP
  SELECT * INTO project_division FROM public.job_budget_divisions WHERE job_id=p_job_id AND archived_at IS NULL AND UPPER(BTRIM(COALESCE(code,'')))=UPPER(BTRIM(catalog.division_code)) LIMIT 1 FOR UPDATE;
  IF project_division.id IS NULL THEN INSERT INTO public.job_budget_divisions(job_id,code,name,sort_order) VALUES(p_job_id,catalog.division_code,catalog.division_name,COALESCE(NULLIF(regexp_replace(catalog.division_code,'\\D','','g'),'')::INTEGER,999)) RETURNING * INTO project_division; division_count:=division_count+1; END IF;
  SELECT * INTO existing_line FROM public.job_budget_lines WHERE job_id=p_job_id AND archived_at IS NULL AND UPPER(BTRIM(COALESCE(cost_code,'')))=UPPER(BTRIM(catalog.cost_code)) LIMIT 1 FOR UPDATE;
  IF existing_line.id IS NULL THEN INSERT INTO public.job_budget_lines(job_id,division,project_division_id,category,is_protected_financial,cost_code,description,budget_amount,budget_change_amount,actual_cost_amount,committed_cost_amount,forecast_to_complete_amount,forecast_final_amount,schedule_of_values_amount,note,sort_order,created_by) VALUES(p_job_id,target_job.division,project_division.id,catalog.category,catalog.is_protected_financial,catalog.cost_code,catalog.description,0,0,0,0,0,0,0,NULLIF(BTRIM(catalog.notes),''),catalog.sort_order,actor_id); added_count:=added_count+1; ELSIF existing_line.project_division_id IS DISTINCT FROM project_division.id OR existing_line.description IS DISTINCT FROM catalog.description OR existing_line.category IS DISTINCT FROM catalog.category OR existing_line.is_protected_financial IS DISTINCT FROM catalog.is_protected_financial THEN UPDATE public.job_budget_lines SET project_division_id=project_division.id,description=catalog.description,category=catalog.category,is_protected_financial=catalog.is_protected_financial,note=COALESCE(NULLIF(BTRIM(catalog.notes),''),note),updated_at=NOW() WHERE id=existing_line.id; aligned_count:=aligned_count+1; END IF;
 END LOOP;
 INSERT INTO public.change_logs(user_id,user_name,table_name,record_id,action,after_data,note) VALUES(actor_id,actor_name,'financial_line_catalogue',p_job_id::TEXT,'update',jsonb_build_object('catalogue_ids',p_catalogue_ids,'divisions_added',division_count,'lines_added',added_count,'lines_aligned',aligned_count),BTRIM(p_reason));
 RETURN jsonb_build_object('divisions_added',division_count,'lines_added',added_count,'lines_aligned',aligned_count);
END; $$;
CREATE OR REPLACE FUNCTION public.replace_financial_line_catalogue(p_rows JSONB,p_reason TEXT) RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ DECLARE actor TEXT:=auth.jwt()->>'sub'; row_data JSONB; saved_count INTEGER:=0; BEGIN IF actor IS NULL OR public.current_user_has_developer_access() IS NOT TRUE THEN RAISE EXCEPTION 'Developer access is required' USING ERRCODE='42501'; END IF; IF jsonb_typeof(p_rows)<>'array' OR jsonb_array_length(p_rows)=0 OR NULLIF(BTRIM(COALESCE(p_reason,'')),'') IS NULL THEN RAISE EXCEPTION 'catalogue rows and an audit reason are required'; END IF; FOR row_data IN SELECT value FROM jsonb_array_elements(p_rows) LOOP IF NULLIF(BTRIM(COALESCE(row_data->>'division_code','')),'') IS NULL OR NULLIF(BTRIM(COALESCE(row_data->>'division_name','')),'') IS NULL OR NULLIF(BTRIM(COALESCE(row_data->>'cost_code','')),'') IS NULL OR NULLIF(BTRIM(COALESCE(row_data->>'description','')),'') IS NULL THEN RAISE EXCEPTION 'each catalogue row needs division code, division name, cost code, and description'; END IF; INSERT INTO public.financial_line_catalogue(division_code,division_name,subdivision_name,cost_code,description,notes,category,is_protected_financial,sort_order,is_active,retired_at,retired_by,retirement_reason) VALUES(BTRIM(row_data->>'division_code'),BTRIM(row_data->>'division_name'),NULLIF(BTRIM(row_data->>'subdivision_name'),''),BTRIM(row_data->>'cost_code'),BTRIM(row_data->>'description'),NULLIF(BTRIM(row_data->>'notes'),''),COALESCE(NULLIF(BTRIM(row_data->>'category'),''),'other'),COALESCE((row_data->>'is_protected_financial')::BOOLEAN,FALSE),COALESCE((row_data->>'sort_order')::INTEGER,0),TRUE,NULL,NULL,NULL) ON CONFLICT (UPPER(BTRIM(cost_code))) DO UPDATE SET division_code=EXCLUDED.division_code,division_name=EXCLUDED.division_name,subdivision_name=EXCLUDED.subdivision_name,description=EXCLUDED.description,notes=EXCLUDED.notes,category=EXCLUDED.category,is_protected_financial=EXCLUDED.is_protected_financial,sort_order=EXCLUDED.sort_order,is_active=TRUE,retired_at=NULL,retired_by=NULL,retirement_reason=NULL,updated_at=NOW(); saved_count:=saved_count+1; END LOOP; INSERT INTO public.change_logs(user_id,table_name,record_id,action,after_data,note) VALUES(actor,'financial_line_catalogue','catalogue','update',jsonb_build_object('rows_processed',saved_count),BTRIM(p_reason)); RETURN saved_count; END; $$;
CREATE OR REPLACE FUNCTION public.retire_financial_line_catalogue_item(p_catalogue_id UUID,p_reason TEXT) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ DECLARE actor TEXT:=auth.jwt()->>'sub'; BEGIN IF actor IS NULL OR public.current_user_has_developer_access() IS NOT TRUE THEN RAISE EXCEPTION 'Developer access is required' USING ERRCODE='42501'; END IF; IF p_catalogue_id IS NULL OR NULLIF(BTRIM(COALESCE(p_reason,'')),'') IS NULL THEN RAISE EXCEPTION 'catalogue line and retirement reason are required'; END IF; UPDATE public.financial_line_catalogue SET is_active=FALSE,retired_at=NOW(),retired_by=actor,retirement_reason=BTRIM(p_reason),updated_at=NOW() WHERE id=p_catalogue_id AND is_active; IF NOT FOUND THEN RAISE EXCEPTION 'active catalogue line not found'; END IF; INSERT INTO public.change_logs(user_id,table_name,record_id,action,note) VALUES(actor,'financial_line_catalogue',p_catalogue_id::TEXT,'update',BTRIM(p_reason)); END; $$;
